import {
  standingRules,
  stopRequestsInForce,
  type DecisionState,
  type FreshnessState,
  type RunState,
  type SessionActivity,
} from '../../core/fold'
import type { TestOutcome } from '../../core/adjacency'
import { handleAt, qualifiedHandle } from '../../core/handle'
import type { RepoRule } from '../../core/index-tier1'
import { lexicalCounts } from '../../core/lexicon'
import { byCodeUnit } from '../../core/order'
import { renderRule } from '../../core/rule-fidelity'
import type { RunLiveness } from '../../core/run-lock'

/**
 * Shared template pieces. Projections are generated files — the header
 * makes hand-editing them a visible bug (BD5).
 */
export const GENERATED_HEADER =
  '<!-- generated by sofar — do not hand-edit; truth lives in events.jsonl -->'

/** The "+N more" sentinel the fold appends when an activity list hits its cap (BD44). */
const MORE_SENTINEL = /^\+(\d+) more$/

/**
 * One-line rendering of derived session activity (task 7.2, BD44):
 * "N files (a, b, +K more), M commands, task changes: 1.2 → done". The file
 * count includes sentinel overflow so it states the true unique-path total.
 */
export function describeActivity(activity: SessionActivity): string {
  const parts: string[] = []
  if (activity.files.length > 0) {
    const more = MORE_SENTINEL.exec(activity.files[activity.files.length - 1]!)
    const count = more !== null ? activity.files.length - 1 + Number(more[1]) : activity.files.length
    parts.push(`${count} file${count === 1 ? '' : 's'} (${activity.files.join(', ')})`)
  }
  if (activity.commands > 0) {
    const failed = activity.failed !== undefined && activity.failed > 0 ? ` (${activity.failed} failed)` : ''
    parts.push(`${activity.commands} command${activity.commands === 1 ? '' : 's'}${failed}`)
  }
  if (activity.last_test !== undefined) parts.push(`tests ${activity.last_test.ok ? 'pass' : 'fail'}`)
  if (activity.task_changes.length > 0) {
    parts.push(`task changes: ${activity.task_changes.join(', ')}`)
  }
  return parts.length > 0 ? parts.join(', ') : '(no mechanical events)'
}

/**
 * One-line rendering of a driver run (session-driver 1.2): what launched the
 * sessions, under which policy, the handoffs by reason, and whether the run
 * is still going. Shared by the digest (budgeted) and the uncapped status so
 * both surfaces describe the same run the same way. Reason order is log
 * order — first seen first — so the line is a pure function of the events.
 *
 * `liveness` is what the run lock said about an UNSTOPPED run
 * (drive-visibility 2.3), and only `sofar status` passes it: a lock is not in
 * the record, so no generated file may render it. Held keeps the record's
 * `running`; free and absent replace it, since "running" is exactly the claim
 * a dead driver's run cannot back.
 */
export function describeRun(run: RunState, liveness?: RunLiveness): string {
  const policy =
    run.policy === 'threshold'
      ? `threshold ${run.threshold_pct ?? '?'}%${run.context_window !== undefined ? ` of ${run.context_window}` : ''}`
      : 'task policy'
  const byReason = new Map<string, number>()
  for (const h of run.handoffs) byReason.set(h.reason, (byReason.get(h.reason) ?? 0) + 1)
  const breakdown = [...byReason].map(([reason, n]) => `${n} ${reason}`).join(', ')
  const n = run.handoffs.length
  // Verifications (r1-fixes 3.1, D19), only when the run recorded any, so an
  // unverified run's line is byte-identical to before the gate existed.
  const passes = run.verifications.filter((v) => v.result === 'pass').length
  const checks =
    run.verifications.length > 0 ? `, ${passes}/${run.verifications.length} verification${run.verifications.length === 1 ? '' : 's'} passed` : ''
  const handoffs = `${n} handoff${n === 1 ? '' : 's'}${breakdown.length > 0 ? ` (${breakdown})` : ''}${checks}`
  // Only the requests the owner must honour (drive-visibility 2.2): one left
  // for a driver that died is not a stop the resumed run is ignoring.
  const requests = stopRequestsInForce(run).length
  const asked = `stop requested${requests > 1 ? ` ${requests} times` : ''}`
  const fate =
    run.stop_reason !== undefined
      ? `stopped: ${run.stop_reason}${run.stop_note !== undefined ? ` — ${run.stop_note}` : ''}`
      : liveness === 'free'
        ? `driver gone — no stop recorded and the run lock on this machine is free${requests > 0 ? `; ${asked}, never acknowledged` : ''}; --resume picks it up`
        : liveness === 'absent'
          ? `liveness unknown — no stop recorded and no run lock for it on this machine${requests > 0 ? `; ${asked}, not yet stopped` : ''}`
          : requests > 0
            ? `running — ${asked}, not yet stopped`
            : 'running'
  // A resumed run says so, and at which epoch; one never resumed renders as before.
  const resumed = run.owner.epoch > 1 ? `, resumed (epoch ${run.owner.epoch})` : ''
  return `run ${run.id} via ${run.adapter}, ${policy}${resumed} — ${handoffs}; ${fate}`
}

/**
 * What `sofar status` lists under a run's line: its permission surface in
 * full and its handoffs and adoptions on one timeline. Shared by the plain
 * and the styled status (drive-visibility 2.3), so the two list the same run
 * the same way.
 */
export function runDetailLines(run: RunState): string[] {
  const lines: string[] = []
  // The surface in FULL, and only here (session-driver 2.4, D8). The
  // digest's Driven line is budgeted and this is the question nobody asks
  // until months later — what were those unattended sessions allowed to
  // do? — so it belongs on the surface that answers questions, not the one
  // that fits in a header. Rules are listed whole: a truncated allow-list
  // is worse than none, because it reads as complete.
  if (run.surface !== undefined) {
    const s = run.surface
    const pinned = [
      s.model !== undefined ? `model ${s.model}` : undefined,
      s.effort !== undefined ? `effort ${s.effort}` : undefined,
    ].filter((p): p is string => p !== undefined)
    lines.push(`  permissions: ${s.permission_mode}${pinned.length > 0 ? `, ${pinned.join(', ')}` : ''}`)
    for (const rule of s.allow) lines.push(`    allow ${rule}`)
    for (const rule of s.deny ?? []) lines.push(`    deny ${rule}`)
  }
  // Handoffs and takeovers on one timeline (drive-visibility 2.2), by
  // time; the sort is stable, so a record with no adoption lists its
  // handoffs exactly as before.
  const timeline: { ts: string; line: string }[] = []
  for (const h of run.handoffs) {
    const task = h.task !== undefined ? `, task ${h.task}` : ''
    const tokens = h.tokens !== undefined ? `, ${h.tokens} tokens` : ''
    const detail = h.detail !== undefined ? ` (${h.detail})` : ''
    timeline.push({ ts: h.ts, line: `  - ${h.ts} session ${h.session_id} — ${h.reason}${task}${tokens}${detail}` })
  }
  // An adoption that did not outrank every one before it never held the
  // run — a race another driver won — and says so.
  let highest = 1
  for (const a of run.adoptions) {
    const lost = a.epoch <= highest ? ', outranked — never in force' : ''
    highest = Math.max(highest, a.epoch)
    timeline.push({ ts: a.ts, line: `  - ${a.ts} resumed — epoch ${a.epoch}${lost}` })
  }
  timeline.sort((a, b) => (a.ts < b.ts ? -1 : a.ts > b.ts ? 1 : 0))
  for (const entry of timeline) lines.push(entry.line)
  return lines
}

/**
 * One-line breakdown of the freshness counters (staleness-detection 2.1):
 * "3 files, 1 task change" — zero-count kinds are omitted. Shared by
 * renderStatus (budgeted line) and renderFullStatus (uncapped staleness
 * section) so both surfaces state the same drift.
 *
 * `commands` is omitted because freshnessTotal no longer sums it
 * (drift-signal D1): a breakdown that itemizes a kind the headline number
 * excludes reads as an arithmetic bug — "1 event since write-back (1 file,
 * 11 commands)". Per-session command counts live on describeActivity above,
 * where they answer what a session DID rather than what it owes.
 */
export function describeFreshness(counts: FreshnessState['events_since_writeback']): string {
  const n = (count: number, noun: string, plural = `${noun}s`) =>
    `${count} ${count === 1 ? noun : plural}`
  const parts: string[] = []
  if (counts.files > 0) parts.push(n(counts.files, 'file'))
  if (counts.tasks > 0) parts.push(n(counts.tasks, 'task change'))
  if (counts.phases > 0) parts.push(n(counts.phases, 'phase change'))
  if (counts.notes > 0) parts.push(n(counts.notes, 'note'))
  if (counts.decisions > 0) parts.push(n(counts.decisions, 'decision'))
  if (counts.memories > 0) parts.push(n(counts.memories, 'promoted memory', 'promoted memories'))
  if (counts.reviews > 0) parts.push(n(counts.reviews, 'review'))
  return parts.join(', ')
}

/**
 * Standing-constraints section (drift-hardening 2.1): every decision carrying
 * a `rule`, rendered VERBATIM — a rule is never clipped and never ages out of
 * the last-5 recent-decisions window. [D<n>·<sfx>] is the decision's 1-based
 * ordinal in log order with its check suffix (r4-fixes U5) — the handle a merge
 * cannot move onto another rule — so a session can cite the law it is obeying. Shared by renderStatus (budgeted) and
 * renderFullStatus (uncapped) so the two surfaces cannot disagree on what the
 * constraints say — the describeFreshness pattern.
 *
 * Budget semantics: whole entries drop with a count pointer; the first entry
 * always renders whole (a budget that could silence every rule would be a
 * clip by other means). Whitespace is collapsed to keep the list shape — that
 * is normalization, not clipping. `retire` (r1-fixes 3.2, D25) is
 * `SOFAR_RETIRE`'s value: false renders rules a later rule replaced.
 * `lead` (r4-fixes A9, core/rule-focus) holds the ordinals of the guarded
 * rules bearing on the focus files: they render first, oldest first, ahead
 * of the focus ranking.
 */
export function standingConstraintLines(
  decisions: readonly DecisionState[],
  budget?: number,
  retire = true,
  focus?: ReadonlySet<string>,
  lead?: ReadonlySet<number>,
): string[] {
  // The digest passes a focus (memory-lead D4): most relevant first, so the
  // budget drops the least relevant rules instead of the newest.
  const inOrder = standingRules(decisions, retire)
  const ranked = focus === undefined ? inOrder : rankByRelevance(inOrder, focus, (d) => `${d.rule} ${d.quote ?? ''}`)
  const standing =
    lead === undefined || lead.size === 0
      ? ranked
      : [...inOrder.filter((d) => lead.has(d.ordinal)), ...ranked.filter((d) => !lead.has(d.ordinal))]
  if (standing.length === 0) return []
  // A quoted rule has a source that outranks its wording (memory-lead D2);
  // the header says so only when one exists, so quote-less records render
  // byte-identically to before.
  const quoted = standing.some((d) => d.quote !== undefined)
  const law = quoted ? 'obey verbatim; where a rule quotes the operator, the quote decides' : 'obey verbatim'
  const lines = [`Standing constraints — ${law} (${standing.length}):`]
  let used = 0
  let shown = 0
  for (const d of standing) {
    const line = `- [${handleAt(decisions, d.ordinal)}] ${renderRule(d.rule, d.quote)}`
    if (budget !== undefined && shown > 0 && used + line.length + 1 > budget) break
    lines.push(line)
    used += line.length + 1
    shown++
  }
  if (shown < standing.length) {
    lines.push(`- …and ${standing.length - shown} more (see decisions.md)`)
  }
  return lines
}

/**
 * Other records' standing rules (memory-lead 2.2, D8), rendered after this
 * record's own inside the constraints block. A rule is the operator's choice
 * for the whole project, and round 1 lost one to the record boundary: filed
 * in bucket-list, it never reached the session homed on trips that reversed
 * it. Own rules keep their budget first; these take `budget` — what own rules
 * left, capped by the caller — most relevant to the focus first, then newest
 * (by ts: ordinals of different records do not compare), whole entries only.
 * With no room for one entry the block is a single pointer line, so a record
 * whose own rules fill the budget still learns the others exist.
 *
 * The same words are one rule: records that restated a rule (the same
 * operator ruling filed twice) render it once under every handle, newest
 * handle last, and a rule this record already renders (`own`, its in-force
 * rules) is not repeated. Counts are of distinct rules.
 */
export function repoRuleLines(
  rules: readonly RepoRule[],
  budget: number,
  focus: ReadonlySet<string>,
  own: readonly DecisionState[] = [],
): string[] {
  const key = (rule: string, quote: string | undefined): string => `${rule.replace(/\s+/g, ' ').trim()}\u0000${(quote ?? '').replace(/\s+/g, ' ').trim()}`
  const mine = new Set(own.filter((d) => d.rule !== undefined).map((d) => key(d.rule!, d.quote)))
  // Ordered by the bare `<slug> D<n>` as before; rendered suffixed (r4-fixes U5).
  const merged = new Map<string, { r: RepoRule; handles: string[]; shown: string[] }>()
  for (const r of [...rules].sort((a, b) => (a.ts === b.ts ? byCodeUnit(`${a.initiative} D${a.ordinal}`, `${b.initiative} D${b.ordinal}`) : a.ts < b.ts ? -1 : 1))) {
    const k = key(r.rule, r.quote)
    if (mine.has(k)) continue
    const seen = merged.get(k)
    const shown = qualifiedHandle(r.initiative, r.ordinal, r.id)
    if (seen === undefined) merged.set(k, { r, handles: [`${r.initiative} D${r.ordinal}`], shown: [shown] })
    else {
      seen.handles.push(`${r.initiative} D${r.ordinal}`)
      seen.shown.push(shown)
      seen.r = r // the newest restatement dates the rule
    }
  }
  if (merged.size === 0) return []
  const ranked = [...merged.values()]
    .map((m) => ({ ...m, handle: m.handles.join(', '), score: relevanceScore(`${m.r.rule} ${m.r.quote ?? ''}`, focus) }))
    .sort((a, b) => b.score - a.score || (a.r.ts === b.r.ts ? byCodeUnit(a.handle, b.handle) : a.r.ts < b.r.ts ? 1 : -1))
  const entries: string[] = []
  let used = 0
  for (const { r, shown } of ranked) {
    const line = `- [${shown.join(', ')}] ${renderRule(r.rule, r.quote)}`
    if (used + line.length + 1 > budget) break
    entries.push(line)
    used += line.length + 1
  }
  const rest = ranked.length - entries.length
  if (entries.length === 0) return [`- …and ${rest} more from other records (their decisions.md)`]
  return [
    `Repo-wide rules from other records (${entries.length} of ${ranked.length}, most relevant first):`,
    ...entries,
    ...(rest > 0 ? [`- …and ${rest} more in other records (their decisions.md)`] : []),
  ]
}

/**
 * Stable relevance order (D4): distinct lexicon terms shared with the focus,
 * most first; ties newest (highest ordinal) first — so with no focus the
 * newest lead, and a budget drops the oldest rather than the newest.
 */
export function rankByRelevance<T extends { ordinal: number }>(items: readonly T[], focus: ReadonlySet<string>, text: (item: T) => string): T[] {
  return items
    .map((item) => ({ item, score: relevanceScore(text(item), focus) }))
    .sort((a, b) => b.score - a.score || b.item.ordinal - a.item.ordinal)
    .map((x) => x.item)
}

/** Distinct lexicon terms (core/lexicon stems) `text` shares with `focus`. */
export function relevanceScore(text: string, focus: ReadonlySet<string>): number {
  return Object.keys(lexicalCounts(text)).filter((t) => focus.has(t)).length
}

/** Join non-empty template sections into a document with a trailing newline. */
export function doc(lines: readonly string[]): string {
  return lines.join('\n').replace(/\n+$/, '') + '\n'
}

/**
 * Truncation-aware clip result (staleness-detection 1.3): budgeted sections
 * that want to KNOW they were cut — the mechanical clipped-summary signal —
 * use the *Detect variants; `clipped` is true only when the budget forced a
 * cut. Detection lives at the render seam because budgets do.
 */
export interface ClipResult {
  text: string
  clipped: boolean
}

/** clip(), reporting whether it cut. */
export function clipDetect(text: string, max: number): ClipResult {
  const oneLine = text.replace(/\s+/g, ' ').trim()
  if (oneLine.length <= max) return { text: oneLine, clipped: false }
  return { text: `${oneLine.slice(0, Math.max(0, max - 1))}…`, clipped: true }
}

/**
 * Collapse whitespace and hard-cap a string's length (budgeted sections of
 * the status projection — BD24). The ellipsis is inside the budget.
 */
export function clip(text: string, max: number): string {
  return clipDetect(text, max).text
}

/**
 * Multi-line budget clip for hand-written blocks, reporting whether it cut:
 * unlike clip() it preserves line structure (e.g. repo.md is prose the
 * author formatted); the truncation marker lands INSIDE the budget so the
 * section total never exceeds it.
 */
export function clipBlockDetect(text: string, budget: number, marker: string): ClipResult {
  const trimmed = text.trim()
  if (trimmed.length <= budget) return { text: trimmed, clipped: false }
  const suffix = `\n${marker}`
  return {
    text: `${trimmed.slice(0, Math.max(0, budget - suffix.length)).trimEnd()}${suffix}`,
    clipped: true,
  }
}

/**
 * Task-level progress across phases (task-drop-state D1).
 *
 * `dropped` is its own term, folded into neither side: counting drops as
 * `done` would inflate the numerator and claim delivery for work nobody
 * built, while quietly subtracting them from `total` would let an
 * initiative reach 100% by dropping its hard half, with the lost scope
 * leaving no trace. So the denominator holds every task ever planned and
 * callers surface the drop count next to it.
 */
export interface TaskProgress {
  done: number
  dropped: number
  /** Every task, drops included — this never shrinks silently. */
  total: number
  /** Genuinely outstanding: total − done − dropped. */
  remaining: number
}

export function taskProgress(
  phases: ReadonlyArray<{ tasks: ReadonlyArray<{ status: string }> }>,
): TaskProgress {
  let done = 0
  let dropped = 0
  let total = 0
  for (const phase of phases) {
    for (const task of phase.tasks) {
      total += 1
      if (task.status === 'done') done += 1
      else if (task.status === 'dropped') dropped += 1
    }
  }
  return { done, dropped, total, remaining: total - done - dropped }
}

/**
 * The headline progress sentence. Without drops this is byte-identical to
 * what it has always been — the injected digest's token budget depends on
 * the common case not growing. With drops it switches to the three-term
 * form, where "0 remaining" is the completion signal that `N/T done` can
 * no longer give honestly.
 */
export function progressText(p: TaskProgress): string {
  if (p.dropped === 0) return `${p.done}/${p.total} tasks done (${pct(p.done, p.total)})`
  return `${p.done} done, ${p.dropped} dropped, ${p.remaining} remaining`
}

/**
 * Compact headline for the width-constrained CLI zooms: `9/10 tasks (90%)`,
 * or `9/10 tasks, 1 dropped (100%)`. The percentage counts drops as
 * resolved, so it agrees with the pie beside it.
 */
export function progressCompact(p: TaskProgress): string {
  const drops = p.dropped === 0 ? '' : `, ${p.dropped} dropped`
  return `${p.done}/${p.total} tasks${drops} (${pct(p.done, p.total, p.dropped)})`
}

/** Compact per-phase fraction: `1/2`, or `1/3 (1 dropped)` when any was. */
export function phaseFraction(p: TaskProgress): string {
  const base = `${p.done}/${p.total}`
  return p.dropped === 0 ? base : `${base} (${p.dropped} dropped)`
}

/**
 * Percentage string that never claims 100% while work remains. Drops count
 * as resolved here — with nothing outstanding the number must be able to
 * reach 100%, which is the whole complaint that motivated this initiative.
 */
export function pct(done: number, total: number, dropped = 0): string {
  if (total === 0) return '0%'
  const resolved = done + dropped
  const raw = Math.floor((resolved / total) * 100)
  return `${resolved === total ? 100 : Math.min(raw, 99)}%`
}

/**
 * One test outcome as a surface line (r1-fixes 2.5, D24): `pass — npm test`,
 * `fail (exit 1) — npm test`. The exit code is shown only on a failure —
 * on a pass it is 0 or unknown, and neither adds a fact.
 */
export function testOutcomeLine(test: TestOutcome): string {
  const exit = !test.ok && test.exit !== undefined ? ` (exit ${test.exit})` : ''
  return `${test.ok ? 'pass' : 'fail'}${exit} — ${test.cmd}`
}

/**
 * The mark every surface puts on a memory whose words are native memory's,
 * imported with the operator's approval (memory-lead D13/D14) — so no reader
 * takes a model's note for the operator's instruction. Empty for the rest.
 */
export function nativeOriginMark(origin: string | undefined): string {
  return origin !== undefined && origin.startsWith('claude-memory:') ? "(from Claude memory, not the operator's words) " : ''
}
