//! The projection templates (rust-core 2.4) — `projections/templates/{shared,
//! plan,decisions,memory,session}.ts` and `projections/generator.ts`, ported
//! verbatim: plan.md, decisions.md, memory.md and sessions/<id>.md are
//! byte-identical to what the TypeScript engine writes (SPEC §Record layout,
//! `docs/HOTPATH.md` §Projection files). Every length, clip and slice is in
//! UTF-16 units and every whitespace rule is JavaScript's (D2, [`crate::text`]).

use std::fs;
use std::io;
use std::path::Path;

use crate::atomic::write_file_atomic;
use crate::fold::{
    DecisionState, FreshnessCounts, InitiativeState, PhaseState, RunState, SessionActivity,
    SessionState, TaskState, TestOutcome,
};
use crate::json::{Json, number_to_string};
use crate::rule_fidelity::{quote_clause, render_rule};
use crate::text::{date_part, js_trim, js_trim_end, one_line, utf16_len, utf16_prefix};

/// The header that makes hand-editing a projection a visible bug (BD5).
pub const GENERATED_HEADER: &str =
    "<!-- generated by sofar — do not hand-edit; truth lives in events.jsonl -->";

// ---------------------------------------------------------------------------
// shared.ts

/// `${n} ${noun}` with an `s` unless n is 1 (`plural` in status.ts and the
/// `n` helper of describeFreshness, whose irregular plural is passed in).
#[must_use]
pub fn plural_of(n: u64, noun: &str, plural: &str) -> String {
    format!("{n} {}", if n == 1 { noun } else { plural })
}

#[must_use]
pub fn plural(n: u64, noun: &str) -> String {
    format!("{n} {noun}{}", if n == 1 { "" } else { "s" })
}

/// The `+N more` sentinel the fold appends when an activity list hits its cap
/// (`/^\+(\d+) more$/`): the count it carries, as JS `Number` would read it.
fn more_sentinel(item: &str) -> Option<f64> {
    let digits = item.strip_prefix('+')?.strip_suffix(" more")?;
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    digits.parse().ok()
}

/// `describeActivity`: "N files (a, b, +K more), M commands, tests pass, task changes: …".
#[must_use]
pub fn describe_activity(activity: &SessionActivity) -> String {
    let mut parts: Vec<String> = Vec::new();
    if !activity.files.is_empty() {
        let last = activity.files.last().expect("non-empty");
        #[allow(clippy::cast_precision_loss, reason = "list lengths are small")]
        let count = match more_sentinel(last) {
            Some(n) => (activity.files.len() - 1) as f64 + n,
            None => activity.files.len() as f64,
        };
        let noun = if count.to_bits() == 1.0f64.to_bits() {
            "file"
        } else {
            "files"
        };
        parts.push(format!(
            "{} {noun} ({})",
            number_to_string(count),
            activity.files.join(", ")
        ));
    }
    if activity.commands > 0 {
        let failed = match activity.failed {
            Some(f) if f > 0 => format!(" ({f} failed)"),
            _ => String::new(),
        };
        parts.push(format!("{}{failed}", plural(activity.commands, "command")));
    }
    if let Some(test) = &activity.last_test {
        parts.push(format!("tests {}", if test.ok { "pass" } else { "fail" }));
    }
    if !activity.task_changes.is_empty() {
        parts.push(format!(
            "task changes: {}",
            activity.task_changes.join(", ")
        ));
    }
    if parts.is_empty() {
        "(no mechanical events)".to_owned()
    } else {
        parts.join(", ")
    }
}

/// What the run lock says about an UNSTOPPED run (drive-visibility 2.3,
/// core/run-lock.ts `RunLiveness`). Only `sofar status` has one: a lock is not
/// in the record, so no generated file may render it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RunLiveness {
    Held,
    Free,
    Absent,
}

/// `stopRequestsInForce` (drive-visibility 2.2): the stop requests whose id
/// sorts after the owner's adoption. One left behind for a driver that died
/// cannot stop the `--resume` that followed it.
#[must_use]
pub fn stop_requests_in_force(run: &RunState) -> Vec<&str> {
    run.stop_requests
        .iter()
        .filter(|id| id.as_str() > run.owner.id.as_str())
        .map(String::as_str)
        .collect()
}

/// `describeRun`: what launched the sessions, under which policy, the
/// handoffs by reason (first seen first), the verifications, and the fate.
/// `liveness` rewrites the fate of an unstopped run (drive-visibility 2.3):
/// held keeps "running"; free and absent replace it.
#[must_use]
#[allow(clippy::too_many_lines, reason = "a verbatim port of one template")]
pub fn describe_run(run: &RunState, liveness: Option<RunLiveness>) -> String {
    let policy = if run.policy == "threshold" {
        format!(
            "threshold {}%{}",
            run.threshold_pct
                .map_or_else(|| "?".to_owned(), number_to_string),
            run.context_window
                .map(|w| format!(" of {}", number_to_string(w)))
                .unwrap_or_default()
        )
    } else {
        "task policy".to_owned()
    };
    let mut by_reason: Vec<(&str, u64)> = Vec::new();
    for h in &run.handoffs {
        match by_reason.iter_mut().find(|(r, _)| *r == h.reason) {
            Some(slot) => slot.1 += 1,
            None => by_reason.push((&h.reason, 1)),
        }
    }
    let breakdown = by_reason
        .iter()
        .map(|(reason, n)| format!("{n} {reason}"))
        .collect::<Vec<_>>()
        .join(", ");
    let n = run.handoffs.len() as u64;
    let passes = run
        .verifications
        .iter()
        .filter(|v| v.result == "pass")
        .count();
    let checks = if run.verifications.is_empty() {
        String::new()
    } else {
        format!(
            ", {passes}/{} verification{} passed",
            run.verifications.len(),
            if run.verifications.len() == 1 {
                ""
            } else {
                "s"
            }
        )
    };
    let handoffs = format!(
        "{}{}{checks}",
        plural(n, "handoff"),
        if breakdown.is_empty() {
            String::new()
        } else {
            format!(" ({breakdown})")
        }
    );
    // Only the requests the owner must honour (drive-visibility 2.2): one
    // left for a driver that died is not a stop the resumed run is ignoring.
    let requests = stop_requests_in_force(run).len();
    let asked = format!(
        "stop requested{}",
        if requests > 1 {
            format!(" {requests} times")
        } else {
            String::new()
        }
    );
    let fate = if let Some(reason) = &run.stop_reason {
        format!(
            "stopped: {reason}{}",
            run.stop_note
                .as_ref()
                .map(|n| format!(" — {n}"))
                .unwrap_or_default()
        )
    } else if liveness == Some(RunLiveness::Free) {
        format!(
            "driver gone — no stop recorded and the run lock on this machine is free{}; --resume picks it up",
            if requests > 0 {
                format!("; {asked}, never acknowledged")
            } else {
                String::new()
            }
        )
    } else if liveness == Some(RunLiveness::Absent) {
        format!(
            "liveness unknown — no stop recorded and no run lock for it on this machine{}",
            if requests > 0 {
                format!("; {asked}, not yet stopped")
            } else {
                String::new()
            }
        )
    } else if requests > 0 {
        format!("running — {asked}, not yet stopped")
    } else {
        "running".to_owned()
    };
    // A resumed run says so, and at which epoch; one never resumed renders as before.
    let resumed = if run.owner.epoch > 1.0 {
        format!(", resumed (epoch {})", number_to_string(run.owner.epoch))
    } else {
        String::new()
    };
    format!(
        "run {} via {}, {policy}{resumed} — {handoffs}; {fate}",
        run.id, run.adapter
    )
}

/// `runDetailLines` (drive-visibility 2.3): what `sofar status` lists under a
/// run's line — its permission surface in full, then its handoffs and
/// adoptions on one timeline, by time (stable, so a record with no adoption
/// lists its handoffs exactly as before).
#[must_use]
pub fn run_detail_lines(run: &RunState) -> Vec<String> {
    let mut lines = Vec::new();
    if let Some(s) = &run.surface {
        let mut pinned: Vec<String> = Vec::new();
        if let Some(model) = surface_field(s, "model") {
            pinned.push(format!("model {model}"));
        }
        if let Some(effort) = surface_field(s, "effort") {
            pinned.push(format!("effort {effort}"));
        }
        lines.push(format!(
            "  permissions: {}{}",
            surface_field(s, "permission_mode").unwrap_or_else(|| "undefined".to_owned()),
            if pinned.is_empty() {
                String::new()
            } else {
                format!(", {}", pinned.join(", "))
            }
        ));
        for rule in surface_list(s, "allow") {
            lines.push(format!("    allow {rule}"));
        }
        for rule in surface_list(s, "deny") {
            lines.push(format!("    deny {rule}"));
        }
    }
    let mut timeline: Vec<(&str, String)> = Vec::new();
    for h in &run.handoffs {
        let task = h
            .task
            .as_ref()
            .map(|t| format!(", task {t}"))
            .unwrap_or_default();
        let tokens = h
            .tokens
            .map(|t| format!(", {} tokens", number_to_string(t)))
            .unwrap_or_default();
        let detail = h
            .detail
            .as_ref()
            .map(|d| format!(" ({d})"))
            .unwrap_or_default();
        timeline.push((
            &h.ts,
            format!(
                "  - {} session {} — {}{task}{tokens}{detail}",
                h.ts, h.session_id, h.reason
            ),
        ));
    }
    // An adoption that did not outrank every one before it never held the
    // run — a race another driver won — and says so.
    let mut highest = 1.0_f64;
    for a in &run.adoptions {
        let lost = if a.epoch <= highest {
            ", outranked — never in force"
        } else {
            ""
        };
        highest = highest.max(a.epoch);
        timeline.push((
            &a.ts,
            format!(
                "  - {} resumed — epoch {}{lost}",
                a.ts,
                number_to_string(a.epoch)
            ),
        ));
    }
    timeline.sort_by(|a, b| a.0.cmp(b.0));
    lines.extend(timeline.into_iter().map(|(_, line)| line));
    lines
}

/// A string field of the run's permission surface, as a template literal prints it.
fn surface_field(surface: &Json, key: &str) -> Option<String> {
    let value = surface.as_obj()?.get(key)?;
    Some(crate::json::js_to_string(value))
}

/// A list field of the run's permission surface (`allow`, `deny`), each entry as a template literal prints it.
fn surface_list(surface: &Json, key: &str) -> Vec<String> {
    surface
        .as_obj()
        .and_then(|o| o.get(key))
        .and_then(Json::as_arr)
        .map(|a| a.iter().map(crate::json::js_to_string).collect())
        .unwrap_or_default()
}

/// `describeFreshness`: "3 files, 1 task change" — zero kinds omitted, commands never.
#[must_use]
pub fn describe_freshness(counts: &FreshnessCounts) -> String {
    let mut parts: Vec<String> = Vec::new();
    if counts.files > 0 {
        parts.push(plural(counts.files, "file"));
    }
    if counts.tasks > 0 {
        parts.push(plural(counts.tasks, "task change"));
    }
    if counts.phases > 0 {
        parts.push(plural(counts.phases, "phase change"));
    }
    if counts.notes > 0 {
        parts.push(plural(counts.notes, "note"));
    }
    if counts.decisions > 0 {
        parts.push(plural(counts.decisions, "decision"));
    }
    if counts.memories > 0 {
        parts.push(plural_of(
            counts.memories,
            "promoted memory",
            "promoted memories",
        ));
    }
    if counts.reviews > 0 {
        parts.push(plural(counts.reviews, "review"));
    }
    parts.join(", ")
}

/// `standingRules`: every decision carrying a rule with its 1-based ordinal.
/// A rule a later rule replaced (`superseded_by`, r1-fixes 3.2, D25) is
/// skipped while `retire` holds — `SOFAR_RETIRE=off` renders it as before.
#[must_use]
pub fn standing_rules(decisions: &[DecisionState], retire: bool) -> Vec<(usize, &DecisionState)> {
    decisions
        .iter()
        .enumerate()
        .filter(|(_, d)| !(retire && d.superseded_by.is_some()))
        .filter(|(_, d)| d.rule.is_some())
        .map(|(i, d)| (i + 1, d))
        .collect()
}

/// `relevanceScore` (memory-lead D4): distinct lexicon stems `text` shares with `focus`.
#[must_use]
pub fn relevance_score(text: &str, focus: &[String]) -> usize {
    // The distinct terms of `lexicalCounts(text)` that are in the focus,
    // without building (or sorting) the counts; no focus scores nothing.
    if focus.is_empty() {
        return 0;
    }
    let mut hit = vec![false; focus.len()];
    crate::lexicon::for_each_term(text, |term| {
        if let Some(i) = focus.iter().position(|f| *f == term) {
            hit[i] = true;
        }
    });
    hit.iter().filter(|h| **h).count()
}

/// `rankByRelevance`: score descending, ties newest (highest ordinal) first — a
/// stable sort, as `Array.prototype.sort` is.
#[must_use]
pub fn rank_by_relevance<T: Clone>(
    items: &[(usize, T)],
    focus: &[String],
    text: impl Fn(&T) -> String,
) -> Vec<(usize, T)> {
    let mut scored: Vec<(usize, (usize, T))> = items
        .iter()
        .map(|(ordinal, item)| {
            (
                relevance_score(&text(item), focus),
                (*ordinal, item.clone()),
            )
        })
        .collect();
    scored.sort_by(|a, b| b.0.cmp(&a.0).then_with(|| b.1.0.cmp(&a.1.0)));
    scored.into_iter().map(|(_, item)| item).collect()
}

/// `nativeOriginMark` (memory-lead D13/D14): the mark every surface puts on
/// a memory whose words are native memory's, so no reader takes a model's
/// note for the operator's instruction. Empty for the rest.
#[must_use]
pub fn native_origin_mark(origin: Option<&str>) -> &'static str {
    if origin.is_some_and(|o| o.starts_with("claude-memory:")) {
        "(from Claude memory, not the operator's words) "
    } else {
        ""
    }
}

/// `retireEnabled`: `SOFAR_RETIRE=off` (also `0`, `false`) renders every
/// decision as if none were retired — read by the render callers, never the fold.
#[must_use]
pub fn retire_enabled() -> bool {
    let Some(raw) = std::env::var_os("SOFAR_RETIRE") else {
        return true;
    };
    let v = raw.to_string_lossy();
    let v = js_trim(&v).to_lowercase();
    !(v == "off" || v == "0" || v == "false")
}

/// `retiredOrdinals` (core/retire.ts): 1-based ordinals no longer in force —
/// superseded, or scoped by `until` to a task that resolved (done or dropped).
#[must_use]
pub fn retired_ordinals(state: &InitiativeState) -> Vec<usize> {
    let resolved: Vec<&str> = state
        .phases
        .iter()
        .flat_map(|p| p.tasks.iter())
        .filter(|t| matches!(t.status.as_str(), "done" | "dropped"))
        .map(|t| t.id.as_str())
        .collect();
    state
        .decisions
        .iter()
        .enumerate()
        .filter(|(_, d)| {
            d.superseded_by.is_some() || d.until.as_deref().is_some_and(|u| resolved.contains(&u))
        })
        .map(|(i, _)| i + 1)
        .collect()
}

/// Another record's rule as `<slug> D<n>·<sfx>` (r4-fixes U5).
fn repo_rule_handle(r: &crate::index_tier1::RepoRule) -> String {
    format!(
        "{} D{}·{}",
        r.initiative,
        number_to_string(r.ordinal),
        handle_suffix(&r.id)
    )
}

/// `standingConstraintLines`: rules VERBATIM (whitespace normalised, never
/// `repoRuleLines` (memory-lead 2.2, D8): other records' standing rules,
/// rendered after this record's own inside the constraints block. The same
/// words are one rule (restatements render once under every handle, newest
/// handle last); a rule this record already renders is not repeated. Most
/// relevant to the focus first, then newest; whole entries only, within
/// `budget`; with no room for one, a single pointer line.
#[must_use]
pub fn repo_rule_lines(
    rules: &[crate::index_tier1::RepoRule],
    budget: i64,
    focus: &[String],
    own: &[&DecisionState],
) -> Vec<String> {
    use crate::text::cmp_utf16;
    let key = |rule: &str, quote: Option<&str>| {
        format!("{}\u{0}{}", one_line(rule), one_line(quote.unwrap_or("")))
    };
    let handle_of = |r: &crate::index_tier1::RepoRule| {
        format!("{} D{}", r.initiative, number_to_string(r.ordinal))
    };
    let mine: std::collections::HashSet<String> = own
        .iter()
        .filter_map(|d| d.rule.as_deref().map(|rule| key(rule, d.quote.as_deref())))
        .collect();
    // Each handle formatted once, not per comparison: ordered by the bare
    // `<slug> D<n>` as before, rendered suffixed (r4-fixes U5).
    let mut sorted: Vec<(&crate::index_tier1::RepoRule, String)> =
        rules.iter().map(|r| (r, handle_of(r))).collect();
    sorted.sort_by(|(a, ha), (b, hb)| {
        if a.ts == b.ts {
            cmp_utf16(ha, hb)
        } else if cmp_utf16(&a.ts, &b.ts).is_lt() {
            std::cmp::Ordering::Less
        } else {
            std::cmp::Ordering::Greater
        }
    });
    // A Map in insertion order, as the TypeScript `Map` iterates.
    #[allow(
        clippy::type_complexity,
        reason = "a TypeScript Map entry, field for field"
    )]
    let mut merged: Vec<(&crate::index_tier1::RepoRule, Vec<String>, Vec<String>)> = Vec::new();
    let mut at: std::collections::HashMap<String, usize> = std::collections::HashMap::new();
    for (r, handle) in sorted {
        let k = key(&r.rule, r.quote.as_deref());
        if mine.contains(&k) {
            continue;
        }
        let shown = repo_rule_handle(r);
        if let Some(&i) = at.get(&k) {
            let (newest, handles, shown_handles) = &mut merged[i];
            handles.push(handle);
            shown_handles.push(shown);
            *newest = r; // the newest restatement dates the rule
        } else {
            at.insert(k, merged.len());
            merged.push((r, vec![handle], vec![shown]));
        }
    }
    if merged.is_empty() {
        return Vec::new();
    }
    let mut ranked: Vec<(&crate::index_tier1::RepoRule, String, usize, String)> = merged
        .into_iter()
        .map(|(r, handles, shown)| {
            let score = relevance_score(
                &format!("{} {}", r.rule, r.quote.as_deref().unwrap_or("")),
                focus,
            );
            (r, handles.join(", "), score, shown.join(", "))
        })
        .collect();
    ranked.sort_by(|a, b| {
        b.2.cmp(&a.2).then_with(|| {
            if a.0.ts == b.0.ts {
                cmp_utf16(&a.1, &b.1)
            } else if cmp_utf16(&a.0.ts, &b.0.ts).is_lt() {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Less
            }
        })
    });
    let mut entries: Vec<String> = Vec::new();
    let mut used: i64 = 0;
    for (r, _, _, shown) in &ranked {
        let line = format!("- [{shown}] {}", render_rule(&r.rule, r.quote.as_deref()));
        #[allow(clippy::cast_possible_wrap, reason = "line lengths are small")]
        let len = utf16_len(&line) as i64;
        if used + len + 1 > budget {
            break;
        }
        entries.push(line);
        used += len + 1;
    }
    let rest = ranked.len() - entries.len();
    if entries.is_empty() {
        return vec![format!(
            "- …and {rest} more from other records (their decisions.md)"
        )];
    }
    let mut out = vec![format!(
        "Repo-wide rules from other records ({} of {}, most relevant first):",
        entries.len(),
        ranked.len()
    )];
    out.extend(entries);
    if rest > 0 {
        out.push(format!(
            "- …and {rest} more in other records (their decisions.md)"
        ));
    }
    out
}

/// clipped); a budget drops whole entries after the first with a pointer.
#[must_use]
pub fn standing_constraint_lines(
    decisions: &[DecisionState],
    budget: Option<usize>,
    retire: bool,
    focus: Option<&[String]>,
) -> Vec<String> {
    // The digest passes a focus (memory-lead D4): most relevant first, so the
    // budget drops the least relevant rules instead of the newest.
    let in_order = standing_rules(decisions, retire);
    let standing: Vec<(usize, &DecisionState)> = match focus {
        None => in_order,
        Some(focus) => rank_by_relevance(&in_order, focus, |d| {
            format!(
                "{} {}",
                d.rule.as_deref().unwrap_or(""),
                d.quote.as_deref().unwrap_or("")
            )
        }),
    };
    if standing.is_empty() {
        return Vec::new();
    }
    // A quoted rule has a source that outranks its wording (memory-lead D2);
    // the header says so only when one exists.
    let quoted = standing.iter().any(|(_, d)| d.quote.is_some());
    let law = if quoted {
        "obey verbatim; where a rule quotes the operator, the quote decides"
    } else {
        "obey verbatim"
    };
    let mut lines = vec![format!(
        "Standing constraints — {law} ({}):",
        standing.len()
    )];
    let mut used = 0;
    let mut shown = 0;
    for (ordinal, d) in &standing {
        // Check-suffixed (r4-fixes U5): the handle a merge cannot move onto another rule.
        let line = format!(
            "- [{}] {}",
            suffixed_handle(*ordinal, &d.id),
            render_rule(d.rule.as_deref().unwrap_or(""), d.quote.as_deref())
        );
        let len = utf16_len(&line);
        if let Some(b) = budget
            && shown > 0
            && used + len + 1 > b
        {
            break;
        }
        lines.push(line);
        used += len + 1;
        shown += 1;
    }
    if shown < standing.len() {
        lines.push(format!(
            "- …and {} more (see decisions.md)",
            standing.len() - shown
        ));
    }
    lines
}

/// `doc`: join, strip trailing newlines, add exactly one.
#[must_use]
pub fn doc(lines: &[String]) -> String {
    let joined = lines.join("\n");
    format!("{}\n", joined.trim_end_matches('\n'))
}

/// `clipDetect`: one-line normalisation, then a hard cap with the ellipsis inside it.
#[must_use]
pub fn clip_detect(text: &str, max: usize) -> (String, bool) {
    let line = one_line(text);
    if utf16_len(&line) <= max {
        return (line, false);
    }
    (
        format!("{}…", utf16_prefix(&line, max.saturating_sub(1))),
        true,
    )
}

#[must_use]
pub fn clip(text: &str, max: usize) -> String {
    clip_detect(text, max).0
}

/// `clipBlockDetect`: keeps line structure; the marker lands INSIDE the budget.
#[must_use]
pub fn clip_block_detect(text: &str, budget: usize, marker: &str) -> (String, bool) {
    let trimmed = js_trim(text);
    if utf16_len(trimmed) <= budget {
        return (trimmed.to_owned(), false);
    }
    let suffix = format!("\n{marker}");
    let keep = budget.saturating_sub(utf16_len(&suffix));
    let head = utf16_prefix(trimmed, keep);
    (format!("{}{suffix}", js_trim_end(&head)), true)
}

/// `taskProgress` (task-drop-state D1): drops are their own term.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TaskProgress {
    pub done: u64,
    pub dropped: u64,
    pub total: u64,
    pub remaining: u64,
}

#[must_use]
pub fn task_progress<'a>(phases: impl IntoIterator<Item = &'a PhaseState>) -> TaskProgress {
    let mut p = TaskProgress {
        done: 0,
        dropped: 0,
        total: 0,
        remaining: 0,
    };
    for phase in phases {
        for task in &phase.tasks {
            p.total += 1;
            if task.status == "done" {
                p.done += 1;
            } else if task.status == "dropped" {
                p.dropped += 1;
            }
        }
    }
    p.remaining = p.total - p.done - p.dropped;
    p
}

/// `progressText`: the headline sentence, byte-identical without drops.
#[must_use]
pub fn progress_text(p: TaskProgress) -> String {
    if p.dropped == 0 {
        format!(
            "{}/{} tasks done ({})",
            p.done,
            p.total,
            pct(p.done, p.total, 0)
        )
    } else {
        format!(
            "{} done, {} dropped, {} remaining",
            p.done, p.dropped, p.remaining
        )
    }
}

/// `phaseFraction`: `1/2`, or `1/3 (1 dropped)`.
#[must_use]
pub fn phase_fraction(p: TaskProgress) -> String {
    let base = format!("{}/{}", p.done, p.total);
    if p.dropped == 0 {
        base
    } else {
        format!("{base} ({} dropped)", p.dropped)
    }
}

/// `pct`: floors, never 100% while work remains; drops count as resolved.
#[must_use]
pub fn pct(done: u64, total: u64, dropped: u64) -> String {
    if total == 0 {
        return "0%".to_owned();
    }
    let resolved = done + dropped;
    #[allow(clippy::cast_precision_loss, reason = "task counts are small")]
    let raw = ((resolved as f64 / total as f64) * 100.0).floor();
    if resolved == total {
        "100%".to_owned()
    } else {
        format!("{}%", number_to_string(raw.min(99.0)))
    }
}

/// `testOutcomeLine` (D24): `pass — npm test`, `fail (exit 1) — npm test`.
#[must_use]
pub fn test_outcome_line(test: &TestOutcome) -> String {
    let exit = match (test.ok, test.exit) {
        (false, Some(code)) => format!(" (exit {})", number_to_string(code)),
        _ => String::new(),
    };
    format!(
        "{}{exit} — {}",
        if test.ok { "pass" } else { "fail" },
        test.cmd
    )
}

fn slug_or_unnamed(state: &InitiativeState) -> &str {
    if state.slug.is_empty() {
        "(unnamed initiative)"
    } else {
        &state.slug
    }
}

// ---------------------------------------------------------------------------
// plan.ts

/// A string field of an optional JSON object (`route.agent`, `verify.cmd`), as
/// the template's `${…}` would print it.
fn json_field(obj: Option<&Json>, key: &str) -> Option<String> {
    obj?.as_obj()?.get(key).map(crate::json::js_to_string)
}

/// `verifySuffix` (r1-fixes 3.1, D19).
fn verify_suffix(task: &TaskState) -> String {
    let mut parts: Vec<String> = Vec::new();
    if let Some(cmd) = json_field(task.verify.as_ref(), "cmd") {
        parts.push(format!("verify: `{cmd}`"));
    }
    if let Some(v) = &task.verification {
        parts.push(if v.result == "pass" {
            format!(
                "verified pass @{} (attempt {})",
                utf16_prefix(&v.checked_head, 7),
                number_to_string(v.attempt)
            )
        } else {
            format!(
                "verification {} (attempt {}{})",
                v.result,
                number_to_string(v.attempt),
                v.exit_code
                    .map(|c| format!(", exit {}", number_to_string(c)))
                    .unwrap_or_default()
            )
        });
    }
    if parts.is_empty() {
        String::new()
    } else {
        format!(" — {}", parts.join("; "))
    }
}

/// `routeSuffix` (session-driver 3.2).
fn route_suffix(task: &TaskState) -> String {
    let Some(route) = task.route.as_ref() else {
        return String::new();
    };
    let mut parts: Vec<String> = Vec::new();
    if let Some(agent) = json_field(Some(route), "agent") {
        parts.push(agent);
    }
    if let Some(model) = json_field(Some(route), "model") {
        parts.push(format!("model {model}"));
    }
    if let Some(effort) = json_field(Some(route), "effort") {
        parts.push(format!("effort {effort}"));
    }
    if parts.is_empty() {
        String::new()
    } else {
        format!(" — route: {}", parts.join(", "))
    }
}

/// `renderPlan`.
#[must_use]
pub fn render_plan(state: &InitiativeState) -> String {
    let mut lines: Vec<String> = vec![GENERATED_HEADER.to_owned(), String::new()];
    lines.push(format!("# Plan: {}", slug_or_unnamed(state)));
    lines.push(String::new());
    lines.push(format!(
        "Goal: {}",
        if state.goal.is_empty() {
            "(none recorded)"
        } else {
            &state.goal
        }
    ));
    lines.push(String::new());
    // The brief is its own file (memory-lead 4.3 part A, D45); brief.md holds it whole.
    if !state.brief.is_empty() {
        lines.push(format!(
            "Brief: the operator's words, {} chars, verbatim in brief.md; `sofar show brief¶<k>` prints one paragraph.",
            utf16_len(&state.brief)
        ));
        lines.push(String::new());
    }
    lines.push(format!(
        "Progress: {}",
        progress_text(task_progress(&state.phases))
    ));
    lines.push(String::new());
    if state.phases.is_empty() {
        lines.push("(no plan recorded yet — call sofar_update_plan)".to_owned());
        lines.push(String::new());
    }
    // A closed phase is one line here and whole in its shard (D45).
    for (k, phase) in state.phases.iter().enumerate() {
        let head = phase_head(phase);
        if is_closed_phase(phase) {
            lines.push(format!("{head} — its tasks in {}", phase_shard(k + 1)));
            lines.push(String::new());
            // Its note stays where its status is read (phase-lifecycle 2.1).
            if let Some(note) = &phase.note {
                lines.push(format!("> {note}"));
                lines.push(String::new());
            }
        } else {
            lines.push(head);
            lines.push(String::new());
            lines.extend(phase_body(phase));
        }
    }
    if let Some(active) = &state.current.active_phase {
        lines.push(format!("Active phase: {active}"));
    }
    if let Some(next) = &state.current.next_action {
        lines.push(format!("Next action: {next}"));
    }
    if let Some(blocked) = &state.current.blocked_on {
        lines.push(format!("Blocked on: {blocked}"));
    }
    doc(&lines)
}

/// `phaseShard`: `phases/P<k>.md`, k counting phases in plan order.
#[must_use]
pub fn phase_shard(k: usize) -> String {
    format!("phases/P{k}.md")
}

/// `isClosedPhase`: done or dropped — one line in the plan index.
#[must_use]
pub fn is_closed_phase(phase: &PhaseState) -> bool {
    phase.status == "done" || phase.status == "dropped"
}

/// `phaseHead`.
#[must_use]
pub fn phase_head(phase: &PhaseState) -> String {
    format!(
        "## {} [{}] — {} done",
        phase.name,
        phase.status,
        phase_fraction(task_progress([phase]))
    )
}

/// `phaseBody`: the note and task lines, then a blank line.
#[must_use]
pub fn phase_body(phase: &PhaseState) -> Vec<String> {
    let mut lines = Vec::new();
    if let Some(note) = &phase.note {
        lines.push(format!("> {note}"));
        lines.push(String::new());
    }
    for task in &phase.tasks {
        let bx = match task.status.as_str() {
            "done" => 'x',
            "dropped" => '-',
            _ => ' ',
        };
        let suffix = match task.status.as_str() {
            "active" | "blocked" | "dropped" => format!(" ({})", task.status),
            _ => String::new(),
        };
        lines.push(format!(
            "- [{bx}] {} {}{suffix}{}{}",
            task.id,
            task.title,
            route_suffix(task),
            verify_suffix(task)
        ));
    }
    lines.push(String::new());
    lines
}

/// `clip` of the index templates: UTF-16 units, an ellipsis in the last one.
fn index_clip(text: &str, max: usize) -> String {
    if utf16_len(text) > max {
        format!("{}…", utf16_prefix(text, max - 1))
    } else {
        text.to_owned()
    }
}

// ---------------------------------------------------------------------------
// decisions.ts

const CROCKFORD: &[u8; 32] = b"0123456789abcdefghjkmnpqrstvwxyz";

/// `handleSuffix` (core/handle.ts, r3-fixes 2.6, D18): 4 Crockford base32
/// chars of sha256(id), its first 20 bits — a merge never changes it.
#[must_use]
pub fn handle_suffix(id: &str) -> String {
    let h = crate::sha256::digest(id.as_bytes());
    let v = (u32::from(h[0]) << 12) | (u32::from(h[1]) << 4) | (u32::from(h[2]) >> 4);
    [15, 10, 5, 0]
        .iter()
        .map(|shift| char::from(CROCKFORD[((v >> shift) & 31) as usize]))
        .collect()
}

/// `suffixedHandle`: `D<ordinal>·<suffix>`, what decisions.md prints.
#[must_use]
pub fn suffixed_handle(ordinal: usize, id: &str) -> String {
    format!("D{ordinal}·{}", handle_suffix(id))
}

/// `handleAt` (r4-fixes U5): the handle every agent-facing line prints for a
/// decision of its own record, `D<n>·<sfx>`; bare `D<n>` only when the record
/// holds no decision at that ordinal.
#[must_use]
pub fn handle_at(decisions: &[DecisionState], ordinal: usize) -> String {
    match ordinal.checked_sub(1).and_then(|i| decisions.get(i)) {
        Some(d) => suffixed_handle(ordinal, &d.id),
        None => format!("D{ordinal}"),
    }
}

/// `qualifiedHandle`: `<slug> D<n>·<sfx>`.
#[must_use]
pub fn qualified_handle(initiative: &str, ordinal: usize, id: &str) -> String {
    format!("{initiative} {}", suffixed_handle(ordinal, id))
}

/// `supersedesHandle`: a recorded `supersedes` (the bare `D<n>` the fold
/// resolved) as the suffixed handle of the earlier decision it names; as
/// recorded otherwise.
#[must_use]
pub fn supersedes_handle(decisions: &[DecisionState], raw: &str, ordinal: usize) -> String {
    let n = raw
        .strip_prefix('D')
        .filter(|d| !d.is_empty() && !d.starts_with('0') && d.bytes().all(|b| b.is_ascii_digit()))
        .and_then(|d| d.parse::<usize>().ok())
        .unwrap_or(0);
    if n > 0 && n < ordinal {
        handle_at(decisions, n)
    } else {
        raw.to_owned()
    }
}

/// `sameDecisionText`: a re-log, not a change — every field but the check.
#[must_use]
pub fn same_decision_text(a: &DecisionState, b: &DecisionState) -> bool {
    a.chose == b.chose
        && a.over == b.over
        && a.because == b.because
        && a.rule == b.rule
        && a.quote == b.quote
        && a.guard == b.guard
        && a.until == b.until
}

/// `relogAliases` (r4-fixes U5): re-logs folded into the entry that replaced
/// them. `absorbed[i]` is the ordinal that renders ordinal `i + 1` (0 when it
/// renders itself); `aliases` maps an entry's ordinal to its alias ordinals,
/// oldest first, in ascending entry order.
#[must_use]
pub fn relog_aliases(decisions: &[DecisionState]) -> (Vec<usize>, Vec<(usize, Vec<usize>)>) {
    let next: Vec<usize> = decisions
        .iter()
        .enumerate()
        .map(|(i, d)| {
            #[allow(clippy::cast_possible_truncation, reason = "ordinals fit usize")]
            let by = d.superseded_by.map_or(0, |b| b as usize);
            if by <= i + 1 {
                return 0;
            }
            match decisions.get(by - 1) {
                Some(r) if same_decision_text(d, r) => by,
                _ => 0,
            }
        })
        .collect();
    let mut absorbed = vec![0usize; decisions.len()];
    let mut aliases: Vec<(usize, Vec<usize>)> = Vec::new();
    for (i, &first) in next.iter().enumerate() {
        if first == 0 {
            continue;
        }
        let mut to = first;
        while next.get(to - 1).is_some_and(|&n| n != 0) {
            to = next[to - 1];
        }
        absorbed[i] = to;
        match aliases.iter_mut().find(|(e, _)| *e == to) {
            Some((_, list)) => list.push(i + 1),
            None => aliases.push((to, vec![i + 1])),
        }
    }
    (absorbed, aliases)
}

/// The aliases `relog_aliases` lists for `ordinal`, if any.
#[must_use]
pub fn aliases_of(aliases: &[(usize, Vec<usize>)], ordinal: usize) -> Option<&[usize]> {
    aliases
        .iter()
        .find(|(e, _)| *e == ordinal)
        .map(|(_, list)| list.as_slice())
}

/// `aliasMark`: `alias D73·abcd, D76·wxyz`.
#[must_use]
pub fn alias_mark(decisions: &[DecisionState], ordinals: &[usize]) -> String {
    let named: Vec<String> = ordinals.iter().map(|&n| handle_at(decisions, n)).collect();
    format!("alias {}", named.join(", "))
}

/// `INDEX_HEAD_MAX`: how much of a decision's `chose` an index line carries.
pub const INDEX_HEAD_MAX: usize = 80;

/// `renderDecisions` — the index (memory-lead 4.3 part A, D45): one line per
/// decision, its full text in decisions/D<n>.md.
#[must_use]
pub fn render_decisions(state: &InitiativeState) -> String {
    let mut lines: Vec<String> = vec![GENERATED_HEADER.to_owned(), String::new()];
    lines.push(format!("# Decisions: {}", slug_or_unnamed(state)));
    lines.push(String::new());
    if state.decisions.is_empty() {
        lines.push("(no decisions logged yet)".to_owned());
    } else {
        lines.push("One line per decision, in log order. Its full text — chose, over, because, the operator's words — is in decisions/D<n>.md, or `sofar show D<n>`.".to_owned());
        lines.push(String::new());
    }
    let retired = retired_ordinals(state);
    // A re-log (r4-fixes U5) is one entry: the newer handle, the older as its alias.
    let (absorbed, aliases) = relog_aliases(&state.decisions);
    for (i, d) in state.decisions.iter().enumerate() {
        let ordinal = i + 1;
        if absorbed[i] != 0 {
            continue;
        }
        // Each entry's own handle, check-suffixed (r3-fixes 2.6, D18), and
        // every handle a line names (r4-fixes U5).
        let handle = suffixed_handle(ordinal, &d.id);
        let alias = aliases_of(&aliases, ordinal);
        let alias_note = alias.map_or_else(String::new, |a| {
            format!(" ({})", alias_mark(&state.decisions, a))
        });
        if let Some(by) = d.superseded_by {
            #[allow(clippy::cast_possible_truncation, reason = "ordinals fit usize")]
            let by = handle_at(&state.decisions, by as usize);
            lines.push(format!("- {handle} — superseded by {by}{alias_note}"));
            continue;
        }
        if let Some(until) = d.until.as_ref().filter(|_| retired.contains(&ordinal)) {
            lines.push(format!(
                "- {handle} — retired: {until} resolved{alias_note}"
            ));
            continue;
        }
        let mut marks: Vec<String> = Vec::new();
        if let Some(until) = &d.until {
            marks.push(format!("until {until}"));
        }
        if let Some(a) = alias {
            marks.push(alias_mark(&state.decisions, a));
        } else if let Some(supersedes) = &d.supersedes {
            marks.push(format!(
                "supersedes {}",
                supersedes_handle(&state.decisions, supersedes, ordinal)
            ));
        } else if let Some(held) = d.link_pending.as_ref().and_then(|l| l.held) {
            #[allow(clippy::cast_possible_truncation, reason = "ordinals fit usize")]
            let held = handle_at(&state.decisions, held as usize);
            marks.push(format!("names {held}, held"));
        }
        let mark = if marks.is_empty() {
            String::new()
        } else {
            format!("({}) ", marks.join("; "))
        };
        // Rule leads (drift-hardening 2.2) and is never cut.
        let what = d.rule.as_ref().map_or_else(
            || format!("chose {}", index_clip(&one_line(&d.chose), INDEX_HEAD_MAX)),
            |r| format!("rule: {}", one_line(r)),
        );
        lines.push(format!("- {handle} {} — {mark}{what}", date_part(&d.ts)));
    }
    doc(&lines)
}

// ---------------------------------------------------------------------------
// memory.ts

/// `MEMORY_HEAD_MAX`: how much of a memory an index line carries.
pub const MEMORY_HEAD_MAX: usize = 80;

/// `renderMemory` — written only when something was promoted; an index since
/// memory-lead D45, each memory whole in memory/M<n>.md.
#[must_use]
pub fn render_memory(state: &InitiativeState) -> String {
    let mut lines: Vec<String> = vec![GENERATED_HEADER.to_owned(), String::new()];
    lines.push(format!(
        "# Promoted to repo memory: {}",
        slug_or_unnamed(state)
    ));
    lines.push(String::new());
    lines.push(format!(
        "Cite these in .sofar/repo.md by qualified handle — `{} M<n>` —",
        if state.slug.is_empty() {
            "<slug>"
        } else {
            &state.slug
        }
    ));
    lines.push(
        "which is how `sofar doctor` sees that a promoted fact reached repo memory.".to_owned(),
    );
    lines.push(
        "One line per memory; its full text is in memory/M<n>.md, or `sofar show M<n>`.".to_owned(),
    );
    lines.push(String::new());
    for (index, memory) in state.memories.iter().enumerate() {
        if let Some(by) = &memory.superseded_by {
            lines.push(format!("- M{} — superseded by {by}", index + 1));
            continue;
        }
        let replaces = memory
            .supersedes
            .as_ref()
            .map(|s| format!("(supersedes {s}) "))
            .unwrap_or_default();
        lines.push(format!(
            "- M{} {} — {replaces}{}{}",
            index + 1,
            date_part(&memory.ts),
            native_origin_mark(memory.origin.as_deref()),
            index_clip(&one_line(&memory.text), MEMORY_HEAD_MAX)
        ));
    }
    doc(&lines)
}

// ---------------------------------------------------------------------------
// shards.ts (memory-lead 4.3 part A, D45)

/// `decisionShard`.
#[must_use]
pub fn decision_shard(ordinal: usize) -> String {
    format!("decisions/D{ordinal}.md")
}

/// `memoryShard`.
#[must_use]
pub fn memory_shard(ordinal: usize) -> String {
    format!("memory/M{ordinal}.md")
}

/// `decisionEntry`: one decision whole, a field a line; handles suffixed, a
/// re-log naming the entry it is an alias of (r4-fixes U5). `relogs` is
/// `relog_aliases` of the state's decisions.
#[must_use]
pub fn decision_entry(
    state: &InitiativeState,
    ordinal: usize,
    retired: &[usize],
    relogs: &(Vec<usize>, Vec<(usize, Vec<usize>)>),
) -> String {
    let d = &state.decisions[ordinal - 1];
    let into = relogs.0.get(ordinal - 1).copied().unwrap_or(0);
    let why = if into != 0 {
        format!(
            " — re-logged as {}, the same decision",
            handle_at(&state.decisions, into)
        )
    } else if let Some(by) = d.superseded_by {
        #[allow(clippy::cast_possible_truncation, reason = "ordinals fit usize")]
        let by = handle_at(&state.decisions, by as usize);
        format!(" — replaced by {by}")
    } else if let Some(until) = d.until.as_ref().filter(|_| retired.contains(&ordinal)) {
        format!(" — retired: {until} resolved")
    } else {
        String::new()
    };
    let mut lines = vec![format!(
        "{} — {}{why}",
        suffixed_handle(ordinal, &d.id),
        date_part(&d.ts)
    )];
    if let Some(rule) = &d.rule {
        lines.push(format!("rule: {rule}"));
    }
    // The operator's words follow the rule they sourced (memory-lead D2).
    if let Some(quote) = &d.quote {
        lines.push(d.rule.as_ref().map_or_else(
            || format!("quote: {quote}"),
            |rule| quote_clause(rule, quote),
        ));
    }
    lines.push(format!("chose: {}", d.chose));
    lines.push(format!("over: {}", d.over));
    lines.push(format!("because: {}", d.because));
    if let Some(guard) = &d.guard {
        lines.push(format!("guard: {guard}"));
    }
    if let Some(check) = &d.check {
        let cmd = check
            .as_obj()
            .and_then(|o| o.get("cmd"))
            .map_or_else(|| "undefined".to_owned(), crate::json::js_to_string);
        lines.push(format!("check: {cmd}"));
    }
    if let Some(alias) = aliases_of(&relogs.1, ordinal) {
        let named: Vec<String> = alias
            .iter()
            .map(|&n| handle_at(&state.decisions, n))
            .collect();
        lines.push(format!("alias: {}", named.join(", ")));
    } else if let Some(supersedes) = &d.supersedes {
        lines.push(format!(
            "supersedes: {}",
            supersedes_handle(&state.decisions, supersedes, ordinal)
        ));
    }
    if let Some(until) = &d.until {
        lines.push(format!("until: {until}"));
    }
    lines.join("\n")
}

/// `memoryEntry`: one memory whole.
#[must_use]
pub fn memory_entry(state: &InitiativeState, ordinal: usize) -> String {
    let m = &state.memories[ordinal - 1];
    let replaced = m
        .superseded_by
        .as_ref()
        .map(|by| format!(" — replaced by {by}"))
        .unwrap_or_default();
    let supersedes = m
        .supersedes
        .as_ref()
        .map(|s| format!(" — supersedes {s}"))
        .unwrap_or_default();
    format!(
        "M{ordinal} — {}{replaced}{supersedes}\n{}{}",
        date_part(&m.ts),
        native_origin_mark(m.origin.as_deref()),
        m.text
    )
}

/// `renderBrief`: brief.md, written only when there is a brief.
#[must_use]
pub fn render_brief(state: &InitiativeState) -> String {
    let mut lines: Vec<String> = vec![
        GENERATED_HEADER.to_owned(),
        String::new(),
        format!("# Brief: {}", slug_or_unnamed(state)),
        String::new(),
        "The operator's words, verbatim. `sofar show brief¶<k>` prints one paragraph.".to_owned(),
        String::new(),
    ];
    lines.extend(state.brief.split('\n').map(str::to_owned));
    doc(&lines)
}

/// `renderShards`: every shard, path relative to the initiative directory, in
/// a fixed order — decisions, memories, then closed phases.
#[must_use]
pub fn render_shards(state: &InitiativeState) -> Vec<(String, String)> {
    let retired = retired_ordinals(state);
    let relogs = relog_aliases(&state.decisions);
    let mut out = Vec::with_capacity(state.decisions.len() + state.memories.len());
    for n in 1..=state.decisions.len() {
        let body = decision_entry(state, n, &retired, &relogs);
        out.push((
            decision_shard(n),
            doc(&[GENERATED_HEADER.to_owned(), String::new(), body]),
        ));
    }
    for n in 1..=state.memories.len() {
        let body = memory_entry(state, n);
        out.push((
            memory_shard(n),
            doc(&[GENERATED_HEADER.to_owned(), String::new(), body]),
        ));
    }
    for (k, phase) in state.phases.iter().enumerate() {
        if is_closed_phase(phase) {
            let mut lines = vec![
                GENERATED_HEADER.to_owned(),
                String::new(),
                phase_head(phase),
                String::new(),
            ];
            lines.extend(phase_body(phase));
            out.push((phase_shard(k + 1), doc(&lines)));
        }
    }
    out
}

// ---------------------------------------------------------------------------
// session.ts

/// `renderSession`.
#[must_use]
pub fn render_session(state: &InitiativeState, session: &SessionState) -> String {
    let mut lines: Vec<String> = vec![GENERATED_HEADER.to_owned(), String::new()];
    lines.push(format!("# Session {}", session.id));
    lines.push(String::new());
    lines.push(format!("- Initiative: {}", slug_or_unnamed(state)));
    lines.push(format!("- Tool: {}", session.tool));
    if let Some(model) = &session.model {
        lines.push(format!("- Model: {model}"));
    }
    lines.push(format!("- Started: {}", session.started));
    let closed = session
        .closed_reason
        .as_ref()
        .map(|r| format!(" (closed: {r})"))
        .unwrap_or_default();
    lines.push(format!(
        "- Ended: {}",
        match &session.ended {
            Some(ended) => format!("{ended}{closed}"),
            None => "(in progress)".to_owned(),
        }
    ));
    if let Some(handoff) = &session.handoff {
        let detail = handoff
            .detail
            .as_ref()
            .map(|d| format!(" ({d})"))
            .unwrap_or_default();
        lines.push(format!(
            "- Driven: run {} — handed off: {}{detail}",
            handoff.run, handoff.reason
        ));
    }
    lines.push(String::new());
    lines.push("## Summary".to_owned());
    lines.push(String::new());
    if let Some(summary) = &session.summary {
        lines.push(summary.clone());
    } else if session.activity.is_some() {
        let fate = if session.ended.is_some() {
            "ended without write-back"
        } else {
            "no write-back yet"
        };
        lines.push(format!(
            "(none recorded — {fate}; derived resume point below)"
        ));
    } else {
        lines.push("(none recorded — session did not write back)".to_owned());
    }
    lines.push(String::new());
    lines.push("## Next action".to_owned());
    lines.push(String::new());
    lines.push(
        session
            .next_action
            .clone()
            .unwrap_or_else(|| "(none recorded)".to_owned()),
    );
    if let Some(activity) = &session.activity {
        lines.push(String::new());
        lines.push("## Activity (derived from mechanical events)".to_owned());
        lines.push(String::new());
        lines.push(format!("- Derived: {}", describe_activity(activity)));
        if !activity.files.is_empty() {
            lines.push("- Files:".to_owned());
            for file in &activity.files {
                lines.push(format!("  - {file}"));
            }
        }
        lines.push(format!(
            "- Commands run: {}{}",
            activity.commands,
            activity
                .failed
                .map(|f| format!(" ({f} failed)"))
                .unwrap_or_default()
        ));
        if let Some(test) = &activity.last_test {
            lines.push(format!("- Last test: {}", test_outcome_line(test)));
        }
        if !activity.task_changes.is_empty() {
            lines.push("- Task changes:".to_owned());
            for change in &activity.task_changes {
                lines.push(format!("  - {change}"));
            }
        }
    }
    doc(&lines)
}

// ---------------------------------------------------------------------------
// generator.ts

/// `sessionFileName`: `id.replace(/[^A-Za-z0-9._-]/g, '_') + '.md'` — per
/// UTF-16 unit, so a supplementary character becomes two underscores.
#[must_use]
pub fn session_file_name(id: &str) -> String {
    let mut name = String::with_capacity(id.len() + 3);
    for unit in id.encode_utf16() {
        match char::from_u32(u32::from(unit)) {
            Some(c) if c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-') => name.push(c),
            _ => name.push('_'),
        }
    }
    name.push_str(".md");
    name
}

/// Atomic replace, skipped when the bytes on disk already match (speed-2 T3).
fn write_if_changed(path: &Path, content: &str) -> io::Result<()> {
    if let Ok(existing) = fs::read(path)
        && existing == content.as_bytes()
    {
        return Ok(());
    }
    write_file_atomic(path, content.as_bytes())
}

/// sha256 over the sources that render a session projection, baked in by
/// build.rs (rust-core 4.4, decision 01M39M4B): a change to any of them keys
/// every projection manifest anew, so every session file is rebuilt.
pub const PROJECTION_FINGERPRINT: &str = env!("SOFAR_PROJECTION_FINGERPRINT");

/// `regenerateProjections`: plan.md, decisions.md, memory.md (only once
/// something is promoted) and sessions/<id>.md per known session, the session
/// files dirty-only (01M39M4B).
pub fn regenerate_projections(initiative_dir: &Path, state: &InitiativeState) -> io::Result<()> {
    regenerate_projections_with(initiative_dir, state, Some(PROJECTION_FINGERPRINT))
}

/// [`regenerate_projections`] with an explicit manifest key: `None` renders
/// and writes every session file (the full regeneration the parity tests
/// compare against).
pub fn regenerate_projections_with(
    initiative_dir: &Path,
    state: &InitiativeState,
    fingerprint: Option<&str>,
) -> io::Result<()> {
    fs::create_dir_all(initiative_dir)?;
    write_if_changed(&initiative_dir.join("plan.md"), &render_plan(state))?;
    write_if_changed(
        &initiative_dir.join("decisions.md"),
        &render_decisions(state),
    )?;
    if !state.memories.is_empty() {
        write_if_changed(&initiative_dir.join("memory.md"), &render_memory(state))?;
    }
    if !state.brief.is_empty() {
        write_if_changed(&initiative_dir.join("brief.md"), &render_brief(state))?;
    }
    let shards = render_shards(state);
    if !state.decisions.is_empty() {
        fs::create_dir_all(initiative_dir.join("decisions"))?;
    }
    if !state.memories.is_empty() {
        fs::create_dir_all(initiative_dir.join("memory"))?;
    }
    if shards.iter().any(|(name, _)| name.starts_with("phases/")) {
        fs::create_dir_all(initiative_dir.join("phases"))?;
    }
    let sessions_dir = initiative_dir.join("sessions");
    if !state.sessions.is_empty() {
        fs::create_dir_all(&sessions_dir)?;
    }
    match fingerprint {
        None => {
            for (name, content) in &shards {
                write_if_changed(&initiative_dir.join(name), content)?;
            }
            for session in &state.sessions {
                write_if_changed(
                    &sessions_dir.join(session_file_name(&session.id)),
                    &render_session(state, session),
                )?;
            }
        }
        Some(fp) if !shards.is_empty() || !state.sessions.is_empty() => {
            regenerate_dirty(initiative_dir, &sessions_dir, state, &shards, fp)?;
        }
        Some(_) => {}
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Dirty-only session files and shards (`regenerateDirty`, 01M39M4B; shards
// since memory-lead D45, keyed by their path and the hash of their bytes):
// render_session reads the slug and its own SessionState only, so a file is
// rewritten only when those inputs, the file on disk, or the manifest key
// moved. The output is byte-identical to a full regeneration; the
// event-by-event parity tests gate that.

const PROJECTION_MANIFEST_VERSION: u32 = 1;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
struct ManifestEntry {
    fp: String,
    size: u64,
    mtime_ms: f64,
}

#[derive(serde::Serialize, serde::Deserialize)]
struct Manifest {
    v: u32,
    engine: String,
    schema: String,
    fingerprint: String,
    entries: std::collections::HashMap<String, ManifestEntry>,
}

/// `sessionInputHash`: sha256 of the canonical JSON of {slug, session}.
#[must_use]
pub fn session_input_hash(slug: &str, session: &SessionState) -> String {
    let mut o = crate::json::Object::with_capacity(2);
    o.insert("slug", Json::Str(slug.to_owned()));
    o.insert("session", session.to_json());
    crate::sha256::hex_digest(crate::json::stringify_canonical(&Json::Obj(o)).as_bytes())
}

fn manifest_path(initiative_dir: &Path) -> Option<std::path::PathBuf> {
    let slug = initiative_dir.file_name()?.to_string_lossy().into_owned();
    let sofar_dir = initiative_dir.parent()?.parent()?;
    Some(
        sofar_dir
            .join(".index")
            .join("projections")
            .join(format!("{slug}.rs.json")),
    )
}

fn file_stat(path: &Path) -> Option<(u64, f64)> {
    let m = fs::metadata(path).ok()?;
    Some((m.len(), crate::index_store::mtime_ms_of(&m)))
}

#[allow(
    clippy::float_cmp,
    reason = "exact equality of a stored stat IS the contract"
)]
fn regenerate_dirty(
    initiative_dir: &Path,
    sessions_dir: &Path,
    state: &InitiativeState,
    shards: &[(String, String)],
    fingerprint: &str,
) -> io::Result<()> {
    let version = crate::snapshot::current_version();
    let path = manifest_path(initiative_dir);
    let prior: std::collections::HashMap<String, ManifestEntry> = path
        .as_ref()
        .and_then(|p| fs::read(p).ok())
        .and_then(|b| serde_json::from_slice::<Manifest>(&b).ok())
        .filter(|m| {
            m.v == PROJECTION_MANIFEST_VERSION
                && m.engine == version.engine
                && m.schema == version.schema
                && m.fingerprint == fingerprint
        })
        .map(|m| m.entries)
        .unwrap_or_default();
    let mut entries = std::collections::HashMap::with_capacity(state.sessions.len());
    let mut changed = false;
    for session in &state.sessions {
        let name = session_file_name(&session.id);
        let file = sessions_dir.join(&name);
        let fp = session_input_hash(&state.slug, session);
        if let Some(before) = prior.get(&name)
            && before.fp == fp
            && file_stat(&file) == Some((before.size, before.mtime_ms))
        {
            entries.insert(name, before.clone());
            continue;
        }
        write_if_changed(&file, &render_session(state, session))?;
        if let Some((size, mtime_ms)) = file_stat(&file) {
            entries.insert(name, ManifestEntry { fp, size, mtime_ms });
        }
        changed = true;
    }
    for (name, content) in shards {
        let file = initiative_dir.join(name);
        let fp = crate::sha256::hex_digest(content.as_bytes());
        if let Some(before) = prior.get(name)
            && before.fp == fp
            && file_stat(&file) == Some((before.size, before.mtime_ms))
        {
            entries.insert(name.clone(), before.clone());
            continue;
        }
        write_if_changed(&file, content)?;
        if let Some((size, mtime_ms)) = file_stat(&file) {
            entries.insert(name.clone(), ManifestEntry { fp, size, mtime_ms });
        }
        changed = true;
    }
    if (changed || entries.len() != prior.len())
        && let Some(path) = path
    {
        let manifest = Manifest {
            v: PROJECTION_MANIFEST_VERSION,
            engine: version.engine,
            schema: version.schema,
            fingerprint: fingerprint.to_owned(),
            entries,
        };
        if let Ok(bytes) = serde_json::to_vec(&manifest)
            && let Some(dir) = path.parent()
            && fs::create_dir_all(dir).is_ok()
        {
            // Derived: an unwritten manifest makes every session dirty next time.
            let _ = write_file_atomic(&path, &bytes);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// r4-fixes U5, the fixture of `test/handle-render.test.ts`: a chain of
    /// re-logs folds whole into its last entry, a plain re-log is an alias
    /// too, and a changed field is a real supersession.
    #[test]
    fn relog_aliases_fold_chains_and_only_word_for_word_copies() {
        let d = |n: usize, rule: Option<&str>, because: &str, by: Option<u64>| DecisionState {
            id: format!("01K00000000000000000000{n:03}"),
            ts: "2026-10-01T00:00:00.000Z".into(),
            chose: "c".into(),
            over: "o".into(),
            because: because.into(),
            rule: rule.map(str::to_owned),
            quote: None,
            guard: None,
            supersedes: None,
            until: None,
            check: None,
            superseded_by: by,
            link_pending: None,
        };
        let decisions = vec![
            d(1, Some("R"), "b", Some(2)),
            d(2, Some("R"), "b", Some(3)),
            d(3, Some("R"), "b", None),
            d(4, Some("S"), "b", Some(5)),
            d(5, Some("S"), "changed", None),
            d(6, None, "b", Some(7)),
            d(7, None, "b", None),
        ];
        let (absorbed, aliases) = relog_aliases(&decisions);
        assert_eq!(absorbed, vec![3, 3, 0, 0, 0, 7, 0]);
        assert_eq!(aliases_of(&aliases, 3), Some(&[1, 2][..]));
        assert_eq!(aliases_of(&aliases, 7), Some(&[6][..]));
        assert_eq!(aliases_of(&aliases, 5), None);
        assert_eq!(
            alias_mark(&decisions, &[1, 2]),
            format!(
                "alias {}, {}",
                suffixed_handle(1, &decisions[0].id),
                suffixed_handle(2, &decisions[1].id)
            )
        );
        assert_eq!(handle_at(&decisions, 9), "D9");
        assert_eq!(
            supersedes_handle(&decisions, "D1", 2),
            handle_at(&decisions, 1)
        );
        assert_eq!(supersedes_handle(&decisions, "D2", 2), "D2");
    }

    /// L4 (rust-core 4.4): the scorer that skips the counts equals the
    /// `lexicalCounts` formula it replaced, on every real-log line.
    #[test]
    fn relevance_score_equals_the_counts_formula() {
        let old = |text: &str, focus: &[String]| {
            crate::lexicon::lexical_counts(text)
                .iter()
                .filter(|(t, _)| focus.iter().any(|f| f == t))
                .count()
        };
        let root =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../.sofar/initiatives");
        let mut texts: Vec<String> = Vec::new();
        for entry in std::fs::read_dir(root).unwrap() {
            if let Ok(t) = std::fs::read_to_string(entry.unwrap().path().join("events.jsonl")) {
                texts.extend(t.lines().step_by(3).map(str::to_owned));
            }
        }
        assert!(texts.len() > 3_000, "{}", texts.len());
        let mut checked = 0;
        for (i, text) in texts.iter().enumerate() {
            let other: Vec<String> =
                crate::lexicon::lexical_counts(&texts[(i * 7 + 3) % texts.len()])
                    .into_iter()
                    .map(|(t, _)| t)
                    .collect();
            let own: Vec<String> = crate::lexicon::lexical_counts(text)
                .into_iter()
                .map(|(t, _)| t)
                .step_by(2)
                .collect();
            let mut dup = own.clone();
            dup.extend(own.iter().cloned());
            let mut mixed = other.clone();
            mixed.extend(own.iter().take(3).cloned());
            for focus in [Vec::new(), other, own, dup, mixed] {
                assert_eq!(relevance_score(text, &focus), old(text, &focus), "{text}");
                checked += 1;
            }
        }
        assert!(checked > 15_000);
    }

    #[test]
    fn clip_is_utf16_and_keeps_the_ellipsis_inside_the_budget() {
        assert_eq!(clip("hello world", 20), "hello world");
        assert_eq!(clip("hello   world", 8), "hello w…");
        assert_eq!(utf16_len(&clip("a\u{1F600}\u{1F600}\u{1F600}", 4)), 4);
        assert_eq!(clip("a\u{1F600}\u{1F600}\u{1F600}", 4), "a\u{1F600}…");
        // A cut inside a pair leaves U+FFFD then the ellipsis, as Node prints it.
        assert_eq!(clip("a\u{1F600}\u{1F600}\u{1F600}", 3), "a\u{FFFD}…");
        assert_eq!(clip("abc", 0), "…");
    }

    #[test]
    fn block_clip_lands_the_marker_inside_the_budget() {
        let (text, cut) = clip_block_detect("  line one\nline two  \n", 100, "…more");
        assert!(!cut);
        assert_eq!(text, "line one\nline two");
        let (text, cut) = clip_block_detect("abcdefghij\nklmnop", 12, "M");
        assert!(cut);
        assert_eq!(text, "abcdefghij\nM");
        assert_eq!(utf16_len(&text), 12);
    }

    #[test]
    fn progress_and_pct_follow_the_typescript_forms() {
        assert_eq!(pct(0, 0, 0), "0%");
        assert_eq!(pct(9, 10, 0), "90%");
        assert_eq!(pct(999, 1000, 0), "99%");
        assert_eq!(pct(9, 10, 1), "100%");
        assert_eq!(pct(1, 3, 0), "33%");
        let p = TaskProgress {
            done: 9,
            dropped: 0,
            total: 10,
            remaining: 1,
        };
        assert_eq!(progress_text(p), "9/10 tasks done (90%)");
        let q = TaskProgress {
            done: 8,
            dropped: 1,
            total: 10,
            remaining: 1,
        };
        assert_eq!(progress_text(q), "8 done, 1 dropped, 1 remaining");
        assert_eq!(phase_fraction(q), "8/10 (1 dropped)");
    }

    #[test]
    fn activity_line_counts_the_sentinel() {
        let a = SessionActivity {
            files: vec!["a".into(), "b".into(), "+3 more".into()],
            commands: 1,
            task_changes: vec!["1.2 → done".into()],
            failed: Some(1),
            last_test: Some(TestOutcome {
                cmd: "npm test".into(),
                ok: false,
                exit: Some(1.0),
            }),
            tests_since_edit: Vec::new(),
        };
        assert_eq!(
            describe_activity(&a),
            "5 files (a, b, +3 more), 1 command (1 failed), tests fail, task changes: 1.2 → done"
        );
        let empty = SessionActivity {
            files: vec![],
            commands: 0,
            task_changes: vec![],
            failed: None,
            last_test: None,
            tests_since_edit: Vec::new(),
        };
        assert_eq!(describe_activity(&empty), "(no mechanical events)");
    }

    #[test]
    fn session_file_names_replace_per_utf16_unit() {
        assert_eq!(session_file_name("abc-1.2_X"), "abc-1.2_X.md");
        assert_eq!(session_file_name("a/b:c"), "a_b_c.md");
        assert_eq!(session_file_name("a\u{1F600}b"), "a__b.md");
        assert_eq!(session_file_name("é"), "_.md");
    }

    #[test]
    fn doc_ends_with_exactly_one_newline() {
        assert_eq!(doc(&["a".into(), String::new(), String::new()]), "a\n");
        assert_eq!(doc(&[]), "\n");
    }
}

#[cfg(test)]
#[allow(
    clippy::format_push_string,
    reason = "test fixtures build log text plainly"
)]
mod dirty_tests {
    //! rust-core 4.4, decision 01M39M4B: dirty-only session projections stay
    //! byte-identical to a full regeneration at every step.
    use super::*;
    use crate::fold::{
        FoldCheckpoint, append_to_checkpoint, empty_state, finalize_fold, replay_decoded,
    };
    use crate::log::decode_lines;
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    const FP: &str = "test-fingerprint";

    fn record_dir(slug: &str) -> PathBuf {
        let root = crate::testing::scratch_dir("dirty");
        let dir = root.join(".sofar/initiatives").join(slug);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn tree(dir: &Path) -> BTreeMap<String, String> {
        fn walk(d: &Path, rel: &str, out: &mut BTreeMap<String, String>) {
            let Ok(entries) = fs::read_dir(d) else { return };
            for e in entries {
                let e = e.unwrap();
                let name = e.file_name().to_string_lossy().into_owned();
                if e.file_type().unwrap().is_dir() {
                    walk(&e.path(), &format!("{rel}{name}/"), out);
                } else {
                    out.insert(
                        format!("{rel}{name}"),
                        fs::read_to_string(e.path()).unwrap(),
                    );
                }
            }
        }
        let mut out = BTreeMap::new();
        walk(dir, "", &mut out);
        out
    }

    fn real_logs(max: usize) -> Vec<(String, Vec<String>)> {
        let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../.sofar/initiatives");
        let mut out = Vec::new();
        for entry in fs::read_dir(dir).unwrap() {
            let path = entry.unwrap().path();
            let Ok(text) = fs::read_to_string(path.join("events.jsonl")) else {
                continue;
            };
            if text.is_empty() || text.len() > max {
                continue;
            }
            let slug = path.file_name().unwrap().to_string_lossy().into_owned();
            out.push((slug, text.lines().map(str::to_owned).collect()));
        }
        out
    }

    fn state_of(lines: &[String], slug: &str) -> InitiativeState {
        let mut s = finalize_fold(&replay_decoded(
            decode_lines(lines.iter().map(String::as_str)),
            slug,
            lines.len(),
        ))
        .state;
        slug.clone_into(&mut s.slug);
        s
    }

    fn replay_and_compare(slug: &str, lines: &[String], step: usize) -> usize {
        let (dirty, full) = (record_dir(slug), record_dir(slug));
        let mut cp: Option<FoldCheckpoint> = None;
        let (mut done, mut steps) = (0, 0);
        while done < lines.len() {
            let n = (done + step).min(lines.len());
            if let Some(c) = cp.as_mut() {
                for line in &lines[done..n] {
                    if !append_to_checkpoint(c, line) {
                        cp = None;
                        break;
                    }
                }
            }
            if cp.is_none() {
                cp = Some(replay_decoded(
                    decode_lines(lines[..n].iter().map(String::as_str)),
                    slug,
                    n,
                ));
            }
            done = n;
            let mut state = finalize_fold(cp.as_ref().unwrap()).state;
            slug.clone_into(&mut state.slug);
            regenerate_projections_with(&dirty, &state, Some(FP)).unwrap();
            regenerate_projections_with(&full, &state, None).unwrap();
            assert_eq!(tree(&dirty), tree(&full), "{slug} after {n} lines");
            steps += 1;
        }
        steps
    }

    #[test]
    fn render_session_reads_only_the_slug_and_its_session() {
        let mut checked = 0;
        for (slug, lines) in real_logs(usize::MAX) {
            let state = state_of(&lines, &slug);
            let mut bare = empty_state();
            bare.slug.clone_from(&state.slug);
            for session in &state.sessions {
                assert_eq!(
                    render_session(&bare, session),
                    render_session(&state, session),
                    "{slug}"
                );
                checked += 1;
            }
        }
        assert!(checked > 200, "{checked}");
    }

    #[test]
    fn replay_is_byte_identical_to_a_full_regeneration_at_every_step() {
        let mut steps = 0;
        for (slug, lines) in real_logs(256 * 1024) {
            let step = if lines.len() <= 300 {
                1
            } else {
                lines.len().div_ceil(150)
            };
            steps += replay_and_compare(&slug, &lines, step);
        }
        assert!(steps > 500, "{steps}");
    }

    fn seeded() -> (PathBuf, InitiativeState) {
        let (slug, lines) = real_logs(usize::MAX)
            .into_iter()
            .find(|(_, l)| l.len() > 50)
            .unwrap();
        let state = state_of(&lines, &slug);
        let dir = record_dir(&slug);
        regenerate_projections_with(&dir, &state, Some(FP)).unwrap();
        (dir, state)
    }

    fn want(state: &InitiativeState) -> BTreeMap<String, String> {
        let dir = record_dir(&state.slug);
        regenerate_projections_with(&dir, state, None).unwrap();
        tree(&dir)
    }

    fn first_session_file(dir: &Path) -> PathBuf {
        fs::read_dir(dir.join("sessions"))
            .unwrap()
            .next()
            .unwrap()
            .unwrap()
            .path()
    }

    #[test]
    fn a_moved_file_a_new_slug_or_a_corrupt_manifest_rewrites() {
        // A hand edit (changed size).
        let (dir, state) = seeded();
        fs::write(first_session_file(&dir), "edited by hand\n").unwrap();
        regenerate_projections_with(&dir, &state, Some(FP)).unwrap();
        assert_eq!(tree(&dir), want(&state), "hand edit");
        // A deleted file.
        let (dir, state) = seeded();
        fs::remove_file(first_session_file(&dir)).unwrap();
        regenerate_projections_with(&dir, &state, Some(FP)).unwrap();
        assert_eq!(tree(&dir), want(&state), "deleted");
        // The slug changes.
        let (dir, state) = seeded();
        let mut renamed = state.clone();
        renamed.slug.push_str("-renamed");
        regenerate_projections_with(&dir, &renamed, Some(FP)).unwrap();
        assert_eq!(tree(&dir), want(&renamed), "slug");
        // A corrupt manifest.
        let (dir, state) = seeded();
        let manifest = manifest_path(&dir).unwrap();
        fs::write(&manifest, "{\"v\":1,").unwrap();
        fs::remove_file(first_session_file(&dir)).unwrap();
        regenerate_projections_with(&dir, &state, Some(FP)).unwrap();
        assert_eq!(tree(&dir), want(&state), "corrupt manifest");
    }

    #[test]
    fn a_fingerprint_change_rewrites_files_the_manifest_would_trust() {
        // Stale every file, then make the manifest agree with the stale files'
        // size and mtime: only the key can force the rewrite.
        let staled = || {
            let (dir, state) = seeded();
            let path = manifest_path(&dir).unwrap();
            let mut manifest: Manifest = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
            for e in fs::read_dir(dir.join("sessions")).unwrap() {
                let p = e.unwrap().path();
                let size = fs::metadata(&p).unwrap().len();
                fs::write(&p, "x".repeat(usize::try_from(size).unwrap())).unwrap();
                let (size, mtime_ms) = file_stat(&p).unwrap();
                let name = p.file_name().unwrap().to_string_lossy().into_owned();
                let entry = manifest.entries.get_mut(&name).unwrap();
                entry.size = size;
                entry.mtime_ms = mtime_ms;
            }
            fs::write(&path, serde_json::to_vec(&manifest).unwrap()).unwrap();
            (dir, state)
        };
        let (dir, state) = staled();
        regenerate_projections_with(&dir, &state, Some(FP)).unwrap();
        assert_ne!(
            tree(&dir),
            want(&state),
            "control: trusted under its own key"
        );
        let (dir, state) = staled();
        regenerate_projections_with(&dir, &state, Some("another-template-build")).unwrap();
        assert_eq!(tree(&dir), want(&state));
    }
}
