//! The status projection (rust-core 2.4) — `projections/templates/status.ts`
//! ported verbatim: [`render_status`] is the `SessionStart` block and the
//! `sofar_get_state` digest under its hard 10,000-unit cap; [`render_full_status`]
//! is plain `sofar status`, uncapped (`docs/HOTPATH.md` §Status block
//! (`renderStatus`) and full status; rust-core D14). The cross-session
//! derivations the templates read (`core/fold.ts`, Phase 11) live here too.
//! Every budget is UTF-16 units and every whitespace rule is JavaScript's (D2).

use crate::fold::{
    DecisionState, InitiativeState, PhaseState, RunState, SessionState, TaskState, freshness_total,
};
use crate::git::GitState;
use std::cell::RefCell;

use crate::lexicon::lexical_counts;
use crate::projections::{
    RunLiveness, clip, clip_block_detect, clip_detect, describe_activity, describe_freshness,
    describe_run, phase_fraction, plural, progress_text, rank_by_relevance, relevance_score,
    repo_rule_lines, retired_ordinals, run_detail_lines, standing_constraint_lines, task_progress,
    test_outcome_line,
};
use crate::text::{
    cmp_utf16, date_part, is_js_whitespace, js_trim, one_line, utf16_len, utf16_prefix,
};

pub const STATUS_CHAR_LIMIT: usize = 6_000;
pub const STATUS_TRUNCATION_MARKER: &str = "…truncated — run sofar status for full detail";
pub const REPO_MEMORY_CHAR_BUDGET: usize = 600;
pub const REPO_MEMORY_TRUNCATION_MARKER: &str = "…truncated — read .sofar/repo.md for the rest";

const SESSION_ID_BUDGET: usize = 120;
const GOAL_BUDGET: usize = 400;
/// The plan's brief (r1-fixes 4.6, L36): a FIXED block after the goal; the rest is in plan.md.
const BRIEF_BUDGET: usize = 1_500;
const BRIEF_HEADER: &str = "Brief — the operator's words, verbatim; the plan is this record's reading of it, and a finished task list does not finish the brief:";
const NEXT_TASK_TITLE_BUDGET: usize = 1_000;
const SIBLING_TITLE_BUDGET: usize = 80;
const MAX_SIBLINGS: usize = 6;
const NEXT_ACTION_BUDGET: usize = 500;
const BLOCKED_BUDGET: usize = 500;
const PHASE_LINE_BUDGET: usize = 100;
const MAX_PHASE_LINES: usize = 12;
const DONE_PHASES_LINE_BUDGET: usize = 220;
const SESSION_SUMMARY_BUDGET: usize = 450;
const MIN_SUMMARY_ROOM: usize = 120;
const MEMORY_BUDGET: usize = 1_100;
const MEMORY_WHOLE_MAX: usize = 2;
const MEMORY_WHOLE_BUDGET: usize = 280;
const MEMORY_HEAD_BUDGET: usize = 80;
const MIN_REPO_MEMORY_ROOM: usize = 300;
const DECISION_WINDOW_BUDGET: usize = 1_000;
const OVERFLOW_RESERVE: usize = 40;
const YIELD_SAFETY: usize = 2;
const MINUTIAE_MIN: usize = 24;
const DERIVED_SESSION_BUDGET: usize = 600;
const DECISION_CHOSE_BUDGET: usize = 90;
const DECISION_RULED_CHOSE_BUDGET: usize = 60;
pub const MAX_DECISIONS: usize = 5;
const REJECTED_OVER_LINE_BUDGET: usize = 70;
const REJECTED_LEDGER_BUDGET: usize = 450;
const STANDING_LEDGER_BUDGET: usize = 2_000;
// Other records' rules (memory-lead 2.2, D8) take what this record's own
// rules leave of STANDING_LEDGER_BUDGET, and never more than this.
const REPO_RULES_BUDGET: usize = 1_200;
const CONFLICT_LINE_BUDGET: usize = 200;
const MAX_CONFLICT_LINES: usize = 8;
const STALENESS_LINE_BUDGET: usize = 200;
const PARALLEL_LINE_BUDGET: usize = 260;
const MAX_PARALLEL_LINES: usize = 3;
/// Pending links (r3-fixes 2.5): the newest rules filed naming nothing they replace.
const MAX_PENDING_LINKS: usize = 3;
const NOTE_LINE_BUDGET: usize = 200;
const MAX_NOTES: usize = 5;
const TASK_FILES_LINE_BUDGET: usize = 300;
const MAX_TASK_FILES: usize = 8;
const NEIGHBOUR_LINE_BUDGET: usize = 200;
const MAX_NEIGHBOURS: usize = 3;
const DRIVEN_LINE_BUDGET: usize = 300;
/// Cap on the sibling-count line (record-integrity 4.3).
pub const UNWRITTEN_SIBLING_CAP: usize = 5;

/// The quick-work lane's slug (`core/lane.ts`, r1-fixes 2.6, D14).
pub const QUICK_LANE: &str = "quick";
/// How many recent lane sessions the `SessionStart` block names.
pub const LANE_RECENT_SESSIONS: usize = 5;

const LANE_HOW_LINES: [&str; 3] = [
    "This branch is bound to no initiative, so the hooks capture edits and commands here — no sofar new, no plan, no write-back.",
    "- Made a decision? sofar_start_session (id below) then sofar_log_decision — one line of why. That is the only ask.",
    "- Project-sized work needs its own record: sofar new <slug> --goal \"<one line>\" (or sofar switch <slug>) — this session follows the branch there.",
];

const READ_BACK_LINE: &str = "Read-back: before acting, restate goal, next action, and standing constraints in one sentence each — if your restatement disagrees with this block, trust the block and say so.";
const FOOTER_LINE: &str = "(generated by sofar — full detail in plan.md, decisions.md, sessions/)";

// ---------------------------------------------------------------------------
// Schema predicates (packages/schema/src/events.ts)

/// `isClosedInitiativeStatus`: done | dropped | superseded.
#[must_use]
pub fn is_closed_initiative_status(s: &str) -> bool {
    matches!(s, "done" | "dropped" | "superseded")
}

/// `isResolvedTaskStatus`: done | dropped.
#[must_use]
pub fn is_resolved_task_status(s: &str) -> bool {
    matches!(s, "done" | "dropped")
}

// ---------------------------------------------------------------------------
// Cross-session derivations (core/fold.ts, Phase 11 / D-P11)

/// A file path touched by more than one still-open session.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FileConflict {
    pub path: String,
    pub sessions: Vec<String>,
}

/// A phase whose tasks are all resolved but that was never closed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StalePhase {
    pub name: String,
    pub status: String,
    pub tasks_done: usize,
}

/// A concurrent session's write-back that lost the `next_action` scalar (task 12.4).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ParallelWriteback {
    pub session_id: String,
    pub tool: String,
    pub ended: String,
    pub next_action: String,
}

/// `latestRun`.
#[must_use]
pub fn latest_run(state: &InitiativeState) -> Option<&RunState> {
    state.runs.last()
}

/// `openSessionFiles`: (session, file) pairs of every live session's activity,
/// the `+N more` sentinel skipped.
#[must_use]
pub fn open_session_files<'a>(
    state: &'a InitiativeState,
    also_live: Option<&str>,
) -> Vec<(&'a str, &'a str)> {
    let mut pairs = Vec::new();
    for session in &state.sessions {
        let live = session.ended.is_none() || also_live == Some(session.id.as_str());
        let Some(activity) = &session.activity else {
            continue;
        };
        if !live {
            continue;
        }
        for file in &activity.files {
            if file.starts_with('+') {
                continue;
            }
            pairs.push((session.id.as_str(), file.as_str()));
        }
    }
    pairs
}

/// `openSessionFileConflicts`: files ≥2 open sessions touched, sorted by
/// path in UTF-16 code-unit order (rust-core D6).
#[must_use]
pub fn open_session_file_conflicts(
    state: &InitiativeState,
    also_live: Option<&str>,
) -> Vec<FileConflict> {
    // File → its slot in `by_file`, so grouping is linear. The scan it
    // replaces made this O(pairs × distinct files): 17% of session-start at
    // team100, a cost only the port had (the TypeScript groups in a Map).
    let mut slot_of: std::collections::HashMap<&str, usize> = std::collections::HashMap::new();
    let mut by_file: Vec<(&str, Vec<String>)> = Vec::new();
    for (session, file) in open_session_files(state, also_live) {
        if let Some(&i) = slot_of.get(file) {
            by_file[i].1.push(session.to_owned());
        } else {
            slot_of.insert(file, by_file.len());
            by_file.push((file, vec![session.to_owned()]));
        }
    }
    let mut conflicts: Vec<FileConflict> = by_file
        .into_iter()
        .filter(|(_, sessions)| sessions.len() >= 2)
        .map(|(path, sessions)| FileConflict {
            path: path.to_owned(),
            sessions,
        })
        .collect();
    conflicts.sort_by(|a, b| cmp_utf16(&a.path, &b.path));
    conflicts
}

/// `overlappingWritebacks`: the wrapped sessions whose `next_action` lost the
/// last-writer race against the reference (the newest write-back, or the
/// named one), newest first.
#[must_use]
pub fn overlapping_writebacks(
    state: &InitiativeState,
    reference_session_id: Option<&str>,
) -> Vec<ParallelWriteback> {
    fn ended(s: &SessionState) -> &str {
        s.ended.as_deref().expect("wrapped")
    }
    fn next(s: &SessionState) -> &str {
        s.next_action.as_deref().expect("wrapped")
    }
    let wrapped: Vec<&SessionState> = state
        .sessions
        .iter()
        .filter(|s| s.ended.is_some() && s.next_action.is_some())
        .collect();
    if wrapped.len() < 2 {
        return Vec::new();
    }
    let mut reference: Option<&SessionState> =
        reference_session_id.and_then(|id| wrapped.iter().copied().find(|s| s.id == id));
    if reference.is_none() {
        let mut best = wrapped[0];
        for s in &wrapped {
            if cmp_utf16(ended(s), ended(best)).is_ge() {
                best = s;
            }
        }
        reference = Some(best);
    }
    let r = reference.expect("set above");
    let mut out: Vec<&SessionState> = wrapped
        .iter()
        .copied()
        .filter(|s| {
            !std::ptr::eq(*s, r)
                && next(s) != next(r)
                && cmp_utf16(&s.started, ended(r)).is_le()
                && cmp_utf16(ended(s), &r.started).is_ge()
        })
        .collect();
    out.sort_by(|a, b| cmp_utf16(ended(b), ended(a)));
    out.into_iter()
        .map(|s| ParallelWriteback {
            session_id: s.id.clone(),
            tool: s.tool.clone(),
            ended: ended(s).to_owned(),
            next_action: next(s).to_owned(),
        })
        .collect()
}

/// `staleActivePhases` (staleness-detection 1.2).
#[must_use]
pub fn stale_active_phases(state: &InitiativeState) -> Vec<StalePhase> {
    state
        .phases
        .iter()
        .filter(|p| p.status != "done" && p.status != "dropped" && !p.tasks.is_empty())
        .filter(|p| p.tasks.iter().all(|t| is_resolved_task_status(&t.status)))
        .map(|p| StalePhase {
            name: p.name.clone(),
            status: p.status.clone(),
            tasks_done: p.tasks.len(),
        })
        .collect()
}

// ---------------------------------------------------------------------------
// status.ts helpers

/// `enforceStatusLimit`: anything over the limit is cut to fit, marker included.
#[must_use]
pub fn enforce_status_limit(text: &str) -> String {
    if utf16_len(text) <= STATUS_CHAR_LIMIT {
        return text.to_owned();
    }
    let marker = format!("\n{STATUS_TRUNCATION_MARKER}\n");
    format!(
        "{}{marker}",
        utf16_prefix(text, STATUS_CHAR_LIMIT - utf16_len(&marker))
    )
}

fn last_with_summary(sessions: &[SessionState]) -> Option<&SessionState> {
    sessions.iter().rev().find(|s| s.summary.is_some())
}

/// `lastUnwrittenWithActivity`: newest → oldest, the first session with
/// activity but no summary, unless a written-back session is newer.
fn last_unwritten_with_activity(sessions: &[SessionState]) -> Option<&SessionState> {
    for session in sessions.iter().rev() {
        if session.summary.is_some() {
            return None;
        }
        if session.activity.is_some() {
            return Some(session);
        }
    }
    None
}

/// `unwrittenSessions`: EVERY session with activity and no summary, newest first.
#[must_use]
pub fn unwritten_sessions(sessions: &[SessionState]) -> Vec<&SessionState> {
    sessions
        .iter()
        .filter(|s| s.summary.is_none() && s.activity.is_some())
        .rev()
        .collect()
}

/// `hasRealAlternative`: `over` is non-blank and not the
/// `(no alternative …` / `(none …` placeholder — `/^\(\s*(no alternative|none)/i`,
/// a non-unicode regex, so the case fold is ASCII-only (P3).
pub fn has_real_alternative(over: &str) -> bool {
    let t = js_trim(over);
    if t.is_empty() {
        return false;
    }
    let Some(rest) = t.strip_prefix('(') else {
        return true;
    };
    let rest = rest.trim_start_matches(is_js_whitespace);
    let lower_starts = |needle: &str| {
        rest.len() >= needle.len()
            && rest.is_char_boundary(needle.len())
            && rest[..needle.len()].eq_ignore_ascii_case(needle)
    };
    !(lower_starts("no alternative") || lower_starts("none"))
}

const fn task_mark(status: &str) -> &'static str {
    match status.as_bytes() {
        b"done" => "[x]",
        b"active" => "[~]",
        b"blocked" => "[!]",
        b"dropped" => "[-]",
        _ => "[ ]",
    }
}

fn phase_mark(phase: &PhaseState, stale_names: &[&str]) -> String {
    if stale_names.contains(&phase.name.as_str()) {
        format!("[{} — all tasks done; mark phase done?]", phase.status)
    } else {
        format!("[{}]", phase.status)
    }
}

/// `taskTestsLine` (D24): the active task's latest test outcome, or the
/// at-least-as-new D19 verification.
fn task_tests_line(state: &InitiativeState, task: &TaskState) -> Option<String> {
    let test = state
        .task_tests
        .iter()
        .find(|(id, _)| *id == task.id)
        .map(|(_, t)| t);
    if let Some(v) = &task.verification
        && test.is_none_or(|t| cmp_utf16(&v.ts, &t.ts).is_ge())
    {
        return Some(format!("tests: verified {} — {}", v.result, v.command));
    }
    test.map(|t| format!("tests: {}", test_outcome_line(&t.outcome)))
}

/// `sessionIdLine`: the adopt-by-id line, or None for a missing/blank id.
#[must_use]
pub fn session_id_line(session_id: Option<&str>) -> Option<String> {
    let id = js_trim(session_id.unwrap_or(""));
    if id.is_empty() {
        return None;
    }
    // Host-neutral (memory-lead 1.1, D3): adopted on Claude Code, passed elsewhere.
    Some(format!(
        "Session: {} — adopted on Claude Code; else pass to sofar_start_session.",
        clip(id, SESSION_ID_BUDGET)
    ))
}

/// An adjacent record (record-index 3.3): another initiative that has worked
/// this one's files.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NeighbourRecord {
    pub initiative: String,
    pub paths: u64,
    pub decisions: u64,
}

/// `StatusOptions` — what the `SessionStart` hook hands the template.
#[derive(Debug, Clone, PartialEq)]
pub struct StatusOptions {
    pub repo_memory: Option<String>,
    pub session_id: Option<String>,
    pub git: Option<GitState>,
    pub neighbours: Vec<NeighbourRecord>,
    /// Every OTHER record's standing rules (memory-lead 2.2, D8), retirement
    /// already applied; empty when the index is unreadable.
    pub repo_rules: Vec<crate::index_tier1::RepoRule>,
    pub notices: Vec<String>,
    pub lane: bool,
    /// `activity !== false`: the D24 test line. `None`/`Some(true)` render it.
    pub activity: Option<bool>,
    /// `retireEnabled()` (r1-fixes 3.2, D25): the TypeScript template reads
    /// `SOFAR_RETIRE` itself; here the caller passes it (templates read no
    /// env), defaulting to on.
    pub retire: bool,
    /// The links tier's input to the travel block (linked-context 5.2);
    /// empty renders zero bytes.
    pub travel: crate::travel::TravelInput,
}

impl Default for StatusOptions {
    fn default() -> Self {
        Self {
            repo_memory: None,
            session_id: None,
            git: None,
            neighbours: Vec::new(),
            repo_rules: Vec::new(),
            notices: Vec::new(),
            lane: false,
            activity: None,
            retire: true,
            travel: crate::travel::TravelInput::default(),
        }
    }
}

/// `SOFAR_LINK_ASK=off` (r3-fixes 2.5, the ablation arm): no pending-link
/// block here and no Stop ask; the write result still names candidates.
#[must_use]
pub fn link_ask_enabled() -> bool {
    std::env::var_os("SOFAR_LINK_ASK").is_none_or(|v| v != "off")
}

/// `pendingLinkLines`: a header naming the answer, then one line per pending
/// rule still in force — newest first, at most `MAX_PENDING_LINKS` — with the
/// candidates still in force.
fn pending_link_lines(state: &InitiativeState, retired: &[usize]) -> Vec<String> {
    let live = |n: usize| {
        state
            .decisions
            .get(n.wrapping_sub(1))
            .is_some_and(|d| d.superseded_by.is_none())
            && !retired.contains(&n)
    };
    let mut pending: Vec<String> = Vec::new();
    for (i, d) in state.decisions.iter().enumerate().rev() {
        let Some(link) = &d.link_pending else {
            continue;
        };
        if !live(i + 1) {
            continue;
        }
        #[allow(clippy::cast_possible_truncation, reason = "ordinals fit usize")]
        let may: Vec<String> = link
            .candidates
            .iter()
            .map(|&n| n as usize)
            .filter(|&n| live(n))
            .map(|n| format!("D{n}"))
            .collect();
        pending.push(if may.is_empty() {
            format!("- D{}", i + 1)
        } else {
            format!("- D{} may replace {}", i + 1, may.join(" or "))
        });
    }
    if pending.is_empty() {
        return Vec::new();
    }
    let shown = pending.len().min(MAX_PENDING_LINKS);
    let mut lines = vec![format!(
        "⚠ Links pending — {} rule(s) filed naming nothing they replace; answer each: `sofar supersedes D<n> <D<m>|none>`",
        pending.len()
    )];
    lines.extend(pending[..shown].iter().cloned());
    if pending.len() > shown {
        lines.push(format!("- …and {} more", pending.len() - shown));
    }
    lines
}

/// `briefLines`: the header, then the brief clipped to `BRIEF_BUDGET` UTF-16 units with the plan.md pointer.
fn brief_lines(state: &InitiativeState) -> Vec<String> {
    let mut lines = vec![BRIEF_HEADER.to_owned()];
    if utf16_len(&state.brief) <= BRIEF_BUDGET {
        lines.extend(state.brief.split('\n').map(str::to_owned));
    } else {
        lines.extend(
            utf16_prefix(&state.brief, BRIEF_BUDGET)
                .split('\n')
                .map(str::to_owned),
        );
        lines.push(format!(
            "…truncated — the whole brief is in .sofar/initiatives/{}/plan.md",
            state.slug
        ));
    }
    lines
}

fn goal_line(state: &InitiativeState) -> String {
    if state.goal.is_empty() {
        "(none recorded)".to_owned()
    } else {
        clip(&state.goal, GOAL_BUDGET)
    }
}

fn phase_head(name: &str) -> &str {
    name.split_once(" — ").map_or(name, |(head, _)| head)
}

/// A section of the digest (memory-lead 1.3, D4): fixed lines, a protected
/// block (constraints, read-back, footer — the cut never lands in them), or
/// a YIELDING renderer handed what the cap leaves, by precedence.
enum Block<'a> {
    Fixed {
        lines: Vec<String>,
        protected: bool,
    },
    Yielding {
        rank: u8,
        preferred: usize,
        render: Box<dyn Fn(usize) -> Vec<String> + 'a>,
        lines: Vec<String>,
    },
}

/// `lines.join('\n').length + 1`, zero for no lines.
fn block_cost(lines: &[String]) -> usize {
    if lines.is_empty() {
        0
    } else {
        lines.iter().map(|l| utf16_len(l)).sum::<usize>() + lines.len()
    }
}

/// `text.replace(/\n+$/, '')`.
fn trim_newlines(text: &str) -> &str {
    text.trim_end_matches('\n')
}

/// `assemble`: fill the yielding blocks by precedence, each with the smaller
/// of its preferred budget and what the cap leaves; then the protected end
/// follows whole, the head cut with the marker if it still overruns.
#[allow(
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    reason = "budgets and lengths are far below i64::MAX units"
)]
fn assemble(mut blocks: Vec<Block<'_>>, limit: usize) -> String {
    let mut used: usize = 0;
    for b in &blocks {
        if let Block::Fixed { lines, .. } = b {
            used += block_cost(lines);
        }
    }
    // Precedence order over the yielding blocks (a stable sort, as JS sorts).
    let mut order: Vec<usize> = blocks
        .iter()
        .enumerate()
        .filter(|(_, b)| matches!(b, Block::Yielding { .. }))
        .map(|(i, _)| i)
        .collect();
    order.sort_by_key(|&i| match &blocks[i] {
        Block::Yielding { rank, .. } => *rank,
        Block::Fixed { .. } => 0,
    });
    for i in order {
        if let Block::Yielding {
            preferred,
            render,
            lines,
            ..
        } = &mut blocks[i]
        {
            let room = limit as i64 - used as i64 - YIELD_SAFETY as i64;
            let budget = (*preferred as i64).min(room);
            *lines = if budget > 0 {
                render(budget as usize)
            } else {
                Vec::new()
            };
            used += block_cost(lines);
        }
    }
    let mut head_lines: Vec<&str> = Vec::new();
    let mut tail_lines: Vec<&str> = Vec::new();
    for b in &blocks {
        match b {
            Block::Fixed { lines, protected } => {
                let into = if *protected {
                    &mut tail_lines
                } else {
                    &mut head_lines
                };
                into.extend(lines.iter().map(String::as_str));
            }
            Block::Yielding { lines, .. } => head_lines.extend(lines.iter().map(String::as_str)),
        }
    }
    let head_joined = head_lines.join("\n");
    let tail_joined = tail_lines.join("\n");
    let head = trim_newlines(&head_joined);
    let tail = trim_newlines(&tail_joined);
    let room = limit as i64 - utf16_len(tail) as i64 - 3;
    if utf16_len(head) as i64 <= room {
        return format!("{head}\n\n{tail}\n");
    }
    let marker = STATUS_TRUNCATION_MARKER;
    let keep = (room - utf16_len(marker) as i64 - 1).max(0) as usize;
    format!("{}\n{marker}\n\n{tail}\n", utf16_prefix(head, keep))
}

/// `focusTask` (D4): the active phase's first active, else pending, else
/// blocked task; with none, the same pick in each open phase in plan order.
fn pick_focus(phase: &PhaseState) -> Option<&TaskState> {
    phase
        .tasks
        .iter()
        .find(|t| t.status == "active")
        .or_else(|| phase.tasks.iter().find(|t| t.status == "pending"))
        .or_else(|| phase.tasks.iter().find(|t| t.status == "blocked"))
}

/// `focusTask`: the task the digest leads with, and the task a session's
/// title names (session-naming D1, `host::session_title`).
#[must_use]
pub fn focus_task(state: &InitiativeState) -> Option<(&TaskState, &PhaseState)> {
    let pick = pick_focus;
    if let Some(name) = state.current.active_phase.as_deref()
        && let Some(active) = state.phases.iter().find(|p| p.name == name)
        && let Some(task) = pick(active)
    {
        return Some((task, active));
    }
    for phase in &state.phases {
        if phase.status == "done" || phase.status == "dropped" {
            continue;
        }
        if let Some(task) = pick(phase) {
            return Some((task, phase));
        }
    }
    None
}

const OPEN_TASK: [&str; 3] = ["pending", "active", "blocked"];
const CLAUSE_BOUNDARIES: [&str; 4] = ["; ", " — ", ": ", " ("];

/// `minutiaeHead` (D4): the text cut at its first clause boundary at or past
/// `MINUTIAE_MIN` UTF-16 units, then clipped to `max`.
#[must_use]
pub fn minutiae_head(text: &str, max: usize) -> String {
    let flat = one_line(text);
    let units: Vec<u16> = flat.encode_utf16().collect();
    let mut cut = units.len();
    for boundary in CLAUSE_BOUNDARIES {
        let needle: Vec<u16> = boundary.encode_utf16().collect();
        // `flat.indexOf(boundary, MINUTIAE_MIN)`
        let mut at = MINUTIAE_MIN;
        while at + needle.len() <= units.len() {
            if units[at..at + needle.len()] == needle[..] {
                if at < cut {
                    cut = at;
                }
                break;
            }
            at += 1;
        }
    }
    clip(&utf16_prefix(&flat, cut), max)
}

/// `memoryLines` (D4): the ranked memories under `budget` — up to
/// `MEMORY_WHOLE_MAX` that share a term with the focus whole, the rest as heads.
#[allow(
    clippy::items_after_statements,
    reason = "the pusher reads best beside its loops"
)]
fn memory_lines(
    ranked: &[(usize, (String, &'static str))],
    focus: &[String],
    budget: usize,
) -> Vec<String> {
    let header = format!("Memory ({}; full text in memory.md):", ranked.len());
    if utf16_len(&header) + 1 + OVERFLOW_RESERVE > budget {
        return Vec::new();
    }
    let mut lines = vec![header.clone()];
    let mut used = utf16_len(&header) + 1;
    let mut shown: Vec<usize> = Vec::new();
    fn try_push(
        line: String,
        ordinal: usize,
        budget: usize,
        used: &mut usize,
        shown: &mut Vec<usize>,
        lines: &mut Vec<String>,
    ) {
        if *used + utf16_len(&line) + 1 + OVERFLOW_RESERVE > budget {
            return;
        }
        *used += utf16_len(&line) + 1;
        lines.push(line);
        shown.push(ordinal);
    }
    for (ordinal, (text, mark)) in ranked.iter().take(MEMORY_WHOLE_MAX) {
        if relevance_score(text, focus) > 0 {
            try_push(
                format!("- [M{ordinal}] {mark}{}", clip(text, MEMORY_WHOLE_BUDGET)),
                *ordinal,
                budget,
                &mut used,
                &mut shown,
                &mut lines,
            );
        }
    }
    for (ordinal, (text, mark)) in ranked {
        if !shown.contains(ordinal) {
            try_push(
                format!("- [M{ordinal}] {mark}{}", clip(text, MEMORY_HEAD_BUDGET)),
                *ordinal,
                budget,
                &mut used,
                &mut shown,
                &mut lines,
            );
        }
    }
    if shown.is_empty() {
        return Vec::new();
    }
    let rest = ranked.len() - shown.len();
    if rest > 0 {
        lines.push(format!("- …and {rest} more in memory.md"));
    }
    lines.push(String::new());
    lines
}

/// JS `\w`.
const fn is_word_char(c: char) -> bool {
    c.is_ascii_alphanumeric() || c == '_'
}

/// Does `bullet` name `<slug> M<n>` at word boundaries for an `n` in `rendered`?
fn names_rendered_memory(bullet: &str, slug: &str, rendered: &[usize]) -> bool {
    let needle = format!("{slug} M");
    let mut from = 0;
    while let Some(rel) = bullet[from..].find(&needle) {
        let at = from + rel;
        let before_ok = !bullet[..at].chars().next_back().is_some_and(is_word_char);
        let digits: String = bullet[at + needle.len()..]
            .chars()
            .take_while(char::is_ascii_digit)
            .collect();
        let after_ok = !bullet[at + needle.len() + digits.len()..]
            .chars()
            .next()
            .is_some_and(is_word_char);
        if before_ok
            && after_ok
            && !digits.is_empty()
            && !digits.starts_with('0')
            && let Ok(n) = digits.parse::<usize>()
            && rendered.contains(&n)
        {
            return true;
        }
        from = at + 1;
    }
    false
}

/// `dropMemoryCopies` (D4): a top-level bullet (with its indented
/// continuation) naming a memory already rendered is that memory's copy.
#[must_use]
#[allow(
    clippy::items_after_statements,
    reason = "the flush reads best beside its loop"
)]
pub fn drop_memory_copies(text: &str, slug: &str, rendered: &[usize]) -> String {
    if rendered.is_empty() || slug.is_empty() {
        return text.to_owned();
    }
    fn flush<'a>(
        bullet: &mut Vec<&'a str>,
        out: &mut Vec<&'a str>,
        slug: &str,
        rendered: &[usize],
    ) {
        if bullet.is_empty() {
            return;
        }
        if !names_rendered_memory(&bullet.join("\n"), slug, rendered) {
            out.extend(bullet.iter().copied());
        }
        bullet.clear();
    }
    let mut out: Vec<&str> = Vec::new();
    let mut bullet: Vec<&str> = Vec::new();
    for line in text.split('\n') {
        let starts_bullet = line.starts_with("- ") || line.starts_with("* ");
        let continuation = !bullet.is_empty()
            && line.starts_with(is_js_whitespace)
            && line.chars().any(|c| !is_js_whitespace(c));
        if starts_bullet {
            flush(&mut bullet, &mut out, slug, rendered);
            bullet.push(line);
        } else if continuation {
            bullet.push(line);
        } else {
            flush(&mut bullet, &mut out, slug, rendered);
            out.push(line);
        }
    }
    flush(&mut bullet, &mut out, slug, rendered);
    out.join("\n")
}

/// `- [D<n>]` / `- [M<n>]` prefix → n.
fn handle_ordinal(line: &str, letter: char) -> Option<usize> {
    let rest = line.strip_prefix("- [")?.strip_prefix(letter)?;
    let end = rest.find(']')?;
    let digits = &rest[..end];
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    digits.parse().ok()
}

/// `renderStatus`: the `SessionStart` block / `get_state` digest (memory-lead
/// 1.3, D4): the next task's spec FIRST and the standing constraints LAST,
/// yielding sections filling what the 6,000-unit cap leaves.
#[must_use]
#[allow(
    clippy::too_many_lines,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    reason = "a verbatim port of one template; budgets are far below i64::MAX units"
)]
pub fn render_status(state: &InitiativeState, options: &StatusOptions) -> String {
    let lane = options.lane;
    let retire = options.retire;
    let retired: Vec<usize> = if retire {
        retired_ordinals(state)
    } else {
        Vec::new()
    };
    let stale_phases = stale_active_phases(state);
    let stale_names: Vec<&str> = stale_phases.iter().map(|p| p.name.as_str()).collect();
    let focus = if lane { None } else { focus_task(state) };
    // Relevance focus (D4): the focus task's title, its phase's name and the
    // next action; empty in the lane. Declared before the blocks that borrow it.
    let focus_text = [
        focus.map_or("", |(t, _)| t.title.as_str()),
        focus.map_or("", |(_, p)| p.name.as_str()),
        if lane {
            ""
        } else {
            state.current.next_action.as_deref().unwrap_or("")
        },
    ]
    .join(" ");
    let focus_terms: Vec<String> = lexical_counts(&focus_text)
        .into_iter()
        .map(|(term, _)| term)
        .collect();
    let rendered_memories: RefCell<Vec<usize>> = RefCell::new(Vec::new());
    // What travel dedupes against (linked-context 5.2): bound as those blocks render.
    let rendered_repo_memory: RefCell<String> = RefCell::new(String::new());
    let rendered_rule_lines: RefCell<Vec<String>> = RefCell::new(Vec::new());
    let mut blocks: Vec<Block<'_>> = Vec::new();
    let fixed = |blocks: &mut Vec<Block<'_>>, lines: Vec<String>| {
        if !lines.is_empty() {
            blocks.push(Block::Fixed {
                lines,
                protected: false,
            });
        }
    };

    // (1) Head.
    let mut head = vec![
        if lane {
            format!(
                "# Sofar: quick-work lane ({})",
                if state.slug.is_empty() {
                    QUICK_LANE
                } else {
                    &state.slug
                }
            )
        } else {
            format!(
                "# Sofar status: {}",
                if state.slug.is_empty() {
                    "(unnamed initiative)"
                } else {
                    &state.slug
                }
            )
        },
        String::new(),
        format!("Goal: {}", goal_line(state)),
        String::new(),
    ];
    if lane {
        head.extend(LANE_HOW_LINES.iter().map(|l| (*l).to_owned()));
        head.push(String::new());
    }
    fixed(&mut blocks, head);

    // (1b) The plan's brief (r1-fixes 4.6, L36), fixed; never rendered before
    // one was recorded.
    if !state.brief.is_empty() && !lane {
        let mut lines = brief_lines(state);
        lines.push(String::new());
        fixed(&mut blocks, lines);
    }

    // (2) The next task's spec.
    if let Some((task, phase)) = focus {
        let label = if task.status == "active" {
            "Current task"
        } else {
            "Next task"
        };
        let mut lines = vec![
            format!(
                "{label}: {}",
                clip(
                    &format!("{} {}", task.id, task.title),
                    NEXT_TASK_TITLE_BUDGET
                )
            ),
            format!(
                "  in {} {} {}",
                clip(&phase.name, PHASE_LINE_BUDGET),
                phase_mark(phase, &stale_names),
                phase_fraction(task_progress([phase]))
            ),
        ];
        if task.status == "active" {
            if let Some((_, files)) = state.task_files.iter().find(|(id, _)| *id == task.id)
                && !files.is_empty()
            {
                let listed = files
                    .iter()
                    .take(MAX_TASK_FILES)
                    .map(String::as_str)
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!(
                    "  {}",
                    clip(&format!("files: {listed}"), TASK_FILES_LINE_BUDGET - 2)
                ));
            }
            if options.activity != Some(false)
                && let Some(tests) = task_tests_line(state, task)
            {
                lines.push(format!("  {}", clip(&tests, TASK_FILES_LINE_BUDGET - 2)));
            }
        }
        let siblings: Vec<&TaskState> = phase
            .tasks
            .iter()
            .filter(|t| t.id != task.id && OPEN_TASK.contains(&t.status.as_str()))
            .collect();
        for t in siblings.iter().take(MAX_SIBLINGS) {
            let mark = if t.status == "pending" {
                String::new()
            } else {
                format!(" ({})", t.status)
            };
            lines.push(format!(
                "  - {}{mark}",
                clip(&format!("{} {}", t.id, t.title), SIBLING_TITLE_BUDGET)
            ));
        }
        if siblings.len() > MAX_SIBLINGS {
            lines.push(format!(
                "  - …and {} more (plan.md)",
                siblings.len() - MAX_SIBLINGS
            ));
        }
        lines.push(String::new());
        fixed(&mut blocks, lines);
    }

    // (3) Next action and the drift beside it.
    let mut state_lines: Vec<String> = Vec::new();
    if !lane && let Some(next_action) = &state.current.next_action {
        state_lines.push(format!(
            "Next action: {}",
            clip(next_action, NEXT_ACTION_BUDGET)
        ));
    }
    let parallel = if lane {
        Vec::new()
    } else {
        overlapping_writebacks(state, None)
    };
    if !parallel.is_empty() {
        state_lines.push(format!(
            "⚠ Parallel write-backs — {} overlapping session(s) also recorded a next action:",
            parallel.len()
        ));
        for w in parallel.iter().take(MAX_PARALLEL_LINES) {
            state_lines.push(format!(
                "- {}",
                clip(
                    &format!(
                        "{}, ended {}: {}",
                        w.tool,
                        date_part(&w.ended),
                        w.next_action
                    ),
                    PARALLEL_LINE_BUDGET
                )
            ));
        }
        if parallel.len() > MAX_PARALLEL_LINES {
            state_lines.push(format!(
                "- …and {} more (run sofar status)",
                parallel.len() - MAX_PARALLEL_LINES
            ));
        }
    }
    let drift = freshness_total(&state.freshness);
    if !lane && drift > 0 && state.freshness.last_writeback_ts.is_some() {
        state_lines.push(clip(
            &format!(
                "⚠ next action may be stale: {drift} event{} since write-back ({})",
                if drift == 1 { "" } else { "s" },
                describe_freshness(&state.freshness.events_since_writeback)
            ),
            STALENESS_LINE_BUDGET,
        ));
    }
    let notes = &state.freshness.notes;
    if !notes.is_empty() {
        let recent = &notes[notes.len().saturating_sub(MAX_NOTES)..];
        let skipped = notes.len() - recent.len();
        let label = if state.freshness.last_writeback_ts.is_some() {
            "Notes since write-back"
        } else {
            "Notes"
        };
        state_lines.push(format!(
            "{label}{}:",
            if skipped > 0 {
                format!(" (last {} of {})", recent.len(), notes.len())
            } else {
                String::new()
            }
        ));
        for n in recent {
            state_lines.push(format!(
                "- {}",
                clip(
                    &format!("{} {}", date_part(&n.ts), n.text),
                    NOTE_LINE_BUDGET
                )
            ));
        }
    }
    if !lane && let Some(blocked) = &state.current.blocked_on {
        state_lines.push(format!("Blocked on: {}", clip(blocked, BLOCKED_BUDGET)));
    }
    // Pending links (r3-fixes 2.5, D15): rules filed naming nothing they
    // replace, each with the in-force rules it may replace, until answered.
    if !lane && link_ask_enabled() {
        state_lines.extend(pending_link_lines(state, &retired));
    }
    let conflicts = open_session_file_conflicts(state, None);
    if !conflicts.is_empty() {
        state_lines.push(format!(
            "⚠ Concurrent edits — {} file(s) touched by multiple open sessions:",
            conflicts.len()
        ));
        for c in conflicts.iter().take(MAX_CONFLICT_LINES) {
            state_lines.push(format!(
                "- {}",
                clip(
                    &format!("{} (sessions {})", c.path, c.sessions.join(", ")),
                    CONFLICT_LINE_BUDGET
                )
            ));
        }
        if conflicts.len() > MAX_CONFLICT_LINES {
            state_lines.push(format!(
                "- …and {} more (run sofar doctor)",
                conflicts.len() - MAX_CONFLICT_LINES
            ));
        }
    }
    if !state_lines.is_empty() {
        state_lines.push(String::new());
        fixed(&mut blocks, state_lines);
    }

    // (3b) Travel — yielding (precedence 3), zero bytes with nothing eligible.
    let seeds = if options.travel.links.is_empty() {
        Vec::new()
    } else {
        crate::travel::travel_seeds(state, focus.map(|(t, _)| t))
    };
    if !seeds.is_empty() {
        let travel = &options.travel;
        let focus_terms_ref = &focus_terms;
        let repo_text = &rendered_repo_memory;
        let rule_lines = &rendered_rule_lines;
        let slug = state.slug.as_str();
        blocks.push(Block::Yielding {
            rank: 3,
            preferred: crate::travel::TRAVEL_BUDGET,
            render: Box::new(move |budget: usize| {
                let shown = crate::travel::TravelShown {
                    rules: crate::travel::rule_handles(&rule_lines.borrow()),
                    memories: crate::travel::repo_memory_handles(&repo_text.borrow()),
                };
                let entries =
                    crate::travel::travel_entries(slug, &seeds, travel, focus_terms_ref, &shown);
                crate::travel::travel_lines(&entries, slug, budget)
            }),
            lines: Vec::new(),
        });
    }

    // (4) The last written-back session — yielding (precedence 5).
    if let Some(last) = last_with_summary(&state.sessions) {
        blocks.push(Block::Yielding {
            rank: 5,
            preferred: SESSION_SUMMARY_BUDGET,
            render: Box::new(move |budget: usize| {
                let header = format!(
                    "Last session ({}, ended {}):",
                    last.tool,
                    last.ended.as_deref().unwrap_or("?")
                );
                let room = budget as i64 - utf16_len(&header) as i64 - 4;
                if room < MIN_SUMMARY_ROOM as i64 {
                    return Vec::new();
                }
                let room = room as usize;
                let summary_text = last.summary.as_deref().expect("has summary");
                let (summary, clipped) = clip_detect(summary_text, room);
                if !clipped {
                    return vec![header, format!("  {summary}"), String::new()];
                }
                let pointer = format!(
                    " (clipped — full text in sessions/{}.md)",
                    clip(&last.id, SESSION_ID_BUDGET)
                );
                vec![
                    header,
                    format!(
                        "  {}{pointer}",
                        clip(summary_text, room.saturating_sub(utf16_len(&pointer)))
                    ),
                    String::new(),
                ]
            }),
            lines: Vec::new(),
        });
    }

    // Driver line (session-driver 1.2).
    if let Some(run) = latest_run(state) {
        fixed(
            &mut blocks,
            vec![
                clip(
                    &format!("Driven: {}", describe_run(run, None)),
                    DRIVEN_LINE_BUDGET,
                ),
                String::new(),
            ],
        );
    }

    if lane && !state.sessions.is_empty() {
        let worked: Vec<&SessionState> = state
            .sessions
            .iter()
            .filter(|s| s.activity.is_some())
            .rev()
            .collect();
        let since = state.sessions.first().map(|s| date_part(&s.started));
        let mut lines = vec![format!(
            "Recent quick work ({}, {}{}{}):",
            plural(state.sessions.len() as u64, "session"),
            plural(state.decisions.len() as u64, "decision"),
            since.map(|s| format!(" since {s}")).unwrap_or_default(),
            if worked.len() > LANE_RECENT_SESSIONS {
                format!("; last {LANE_RECENT_SESSIONS}")
            } else {
                String::new()
            }
        )];
        for s in worked.iter().take(LANE_RECENT_SESSIONS) {
            lines.push(format!(
                "- {}",
                clip(
                    &format!(
                        "{} {} — {}",
                        date_part(&s.started),
                        s.tool,
                        describe_activity(s.activity.as_ref().expect("filtered"))
                    ),
                    DERIVED_SESSION_BUDGET
                )
            ));
        }
        lines.push(String::new());
        fixed(&mut blocks, lines);
    }
    let unwritten = if lane {
        None
    } else {
        last_unwritten_with_activity(&state.sessions)
    };
    if let Some(u) = unwritten {
        let fate = if u.ended.is_some() {
            "ended without write-back"
        } else {
            "open, no write-back yet"
        };
        let closed = u
            .closed_reason
            .as_ref()
            .map(|r| format!(", closed: {r}"))
            .unwrap_or_default();
        fixed(
            &mut blocks,
            vec![
                clip(
                    &format!(
                        "Last session ({}{closed}) {fate} — derived: {}",
                        u.tool,
                        describe_activity(u.activity.as_ref().expect("has activity"))
                    ),
                    DERIVED_SESSION_BUDGET,
                ),
                format!(
                    "  (details in sessions/{}.md)",
                    clip(&u.id, SESSION_ID_BUDGET)
                ),
                String::new(),
            ],
        );
    }
    let all_unwritten = if lane {
        Vec::new()
    } else {
        unwritten_sessions(&state.sessions)
    };
    let others: Vec<&SessionState> = all_unwritten
        .into_iter()
        .filter(|s| unwritten.is_none_or(|u| u.id != s.id))
        .collect();
    if !others.is_empty() {
        let named: Vec<String> = others
            .iter()
            .take(UNWRITTEN_SIBLING_CAP)
            .map(|s| clip(&s.id, SESSION_ID_BUDGET))
            .collect();
        let more = if others.len() > named.len() {
            format!(", +{} more", others.len() - named.len())
        } else {
            String::new()
        };
        fixed(
            &mut blocks,
            vec![
                clip(
                    &format!(
                        "⚠ {} other session(s) did work without writing back: {}{more}",
                        others.len(),
                        named.join(", ")
                    ),
                    DERIVED_SESSION_BUDGET,
                ),
                String::new(),
            ],
        );
    }

    // (5) Phases and progress.
    if !lane && !state.phases.is_empty() {
        let open: Vec<&PhaseState> = state
            .phases
            .iter()
            .filter(|p| p.status != "done" && p.status != "dropped")
            .collect();
        let done_phases: Vec<&PhaseState> =
            state.phases.iter().filter(|p| p.status == "done").collect();
        let dropped_phases: Vec<&PhaseState> = state
            .phases
            .iter()
            .filter(|p| p.status == "dropped")
            .collect();
        let mut lines = vec!["Phases:".to_owned()];
        for phase in open.iter().take(MAX_PHASE_LINES) {
            lines.push(format!(
                "- {} {} {}",
                clip(&phase.name, PHASE_LINE_BUDGET),
                phase_mark(phase, &stale_names),
                phase_fraction(task_progress([*phase]))
            ));
        }
        if open.len() > MAX_PHASE_LINES {
            lines.push(format!(
                "- …and {} more phases (see plan.md)",
                open.len() - MAX_PHASE_LINES
            ));
        }
        if !done_phases.is_empty() {
            let p = task_progress(done_phases.iter().copied());
            let names = done_phases
                .iter()
                .map(|ph| phase_head(&ph.name))
                .collect::<Vec<_>>()
                .join(", ");
            lines.push(clip(
                &format!("- done: {names} ({}/{} tasks)", p.done, p.total),
                DONE_PHASES_LINE_BUDGET,
            ));
        }
        if !dropped_phases.is_empty() {
            let p = task_progress(dropped_phases.iter().copied());
            let names = dropped_phases
                .iter()
                .map(|ph| phase_head(&ph.name))
                .collect::<Vec<_>>()
                .join(", ");
            lines.push(clip(
                &format!("- dropped: {names} ({} tasks)", p.total),
                DONE_PHASES_LINE_BUDGET,
            ));
        }
        lines.push(format!(
            "Progress: {} across {} phase(s)",
            progress_text(task_progress(&state.phases)),
            state.phases.len()
        ));
        lines.push(String::new());
        fixed(&mut blocks, lines);
    }

    // (6) Memory — yielding (precedence 1).
    // (text, native-origin mark): the mark rides every rendered line
    // (memory-lead D13/D14); relevance reads the text alone.
    let live_memories: Vec<(usize, (String, &'static str))> = state
        .memories
        .iter()
        .enumerate()
        .filter(|(_, m)| m.superseded_by.is_none())
        .map(|(i, m)| {
            (
                i + 1,
                (
                    m.text.clone(),
                    crate::projections::native_origin_mark(m.origin.as_deref()),
                ),
            )
        })
        .collect();
    if !live_memories.is_empty() {
        let ranked = rank_by_relevance(&live_memories, &focus_terms, |(text, _)| text.clone());
        let focus_terms_ref = &focus_terms;
        let rendered = &rendered_memories;
        blocks.push(Block::Yielding {
            rank: 1,
            preferred: MEMORY_BUDGET,
            render: Box::new(move |budget: usize| {
                rendered.borrow_mut().clear();
                let lines = memory_lines(&ranked, focus_terms_ref, budget);
                for line in &lines {
                    if let Some(n) = handle_ordinal(line, 'M') {
                        rendered.borrow_mut().push(n);
                    }
                }
                lines
            }),
            lines: Vec::new(),
        });
    }

    // (7) Repo memory — yielding (precedence 2).
    let repo_memory = js_trim(options.repo_memory.as_deref().unwrap_or("")).to_owned();
    if !repo_memory.is_empty() {
        let rendered = &rendered_memories;
        let repo_text = &rendered_repo_memory;
        let slug = state.slug.clone();
        blocks.push(Block::Yielding {
            rank: 2,
            preferred: REPO_MEMORY_CHAR_BUDGET,
            render: Box::new(move |budget: usize| {
                let kept_full = drop_memory_copies(&repo_memory, &slug, &rendered.borrow());
                let kept = js_trim(&kept_full);
                if kept.is_empty() || budget < MIN_REPO_MEMORY_ROOM {
                    return Vec::new();
                }
                let header = "Repo memory (.sofar/repo.md):";
                let text = clip_block_detect(
                    kept,
                    budget.saturating_sub(utf16_len(header) + 2),
                    REPO_MEMORY_TRUNCATION_MARKER,
                )
                .0;
                repo_text.borrow_mut().clone_from(&text);
                vec![header.to_owned(), text, String::new()]
            }),
            lines: Vec::new(),
        });
    }

    // (8) The decision index with minutiae dropped — yielding (precedence 3).
    let rules = standing_constraint_lines(
        &state.decisions,
        Some(STANDING_LEDGER_BUDGET),
        retire,
        Some(&focus_terms),
    );
    let shown_rules: Vec<usize> = rules
        .iter()
        .filter_map(|line| handle_ordinal(line, 'D'))
        .collect();
    if !state.decisions.is_empty() {
        let in_force: Vec<(usize, &DecisionState)> = state
            .decisions
            .iter()
            .enumerate()
            .map(|(i, d)| (i + 1, d))
            .filter(|(ordinal, _)| !retired.contains(ordinal))
            .collect();
        let recent = &in_force[in_force.len().saturating_sub(MAX_DECISIONS)..];
        let older_count = in_force.len() - recent.len();
        let count = if older_count > 0 {
            format!("last {} of {}", recent.len(), in_force.len())
        } else {
            in_force.len().to_string()
        };
        let window_header = format!(
            "Recent decisions ({}; full text in decisions.md):",
            if retired.is_empty() {
                count
            } else {
                format!("{count} in force, {} retired", retired.len())
            }
        );
        let window_entries: Vec<String> = recent
            .iter()
            .map(|(ordinal, d)| {
                let ordinal = *ordinal;
                let is_ruled = d.rule.is_some() && shown_rules.contains(&ordinal);
                let chose = minutiae_head(
                    &d.chose,
                    if is_ruled {
                        DECISION_RULED_CHOSE_BUDGET
                    } else {
                        DECISION_CHOSE_BUDGET
                    },
                );
                let over = if has_real_alternative(&d.over) {
                    format!(
                        " — over {}",
                        minutiae_head(&d.over, REJECTED_OVER_LINE_BUDGET)
                    )
                } else {
                    String::new()
                };
                let mut marks: Vec<String> = Vec::new();
                if is_ruled {
                    marks.push("rule below".to_owned());
                }
                if retire && let Some(supersedes) = &d.supersedes {
                    marks.push(format!("supersedes {supersedes}"));
                }
                let mark = if marks.is_empty() {
                    String::new()
                } else {
                    format!(" ({})", marks.join("; "))
                };
                format!("- [D{ordinal}] {}{mark} {chose}{over}", date_part(&d.ts))
            })
            .collect();
        let rejected: Vec<(usize, &DecisionState)> = in_force[..older_count]
            .iter()
            .copied()
            .filter(|(_, d)| has_real_alternative(&d.over))
            .collect();
        let ledger_header = format!(
            "Earlier rejected approaches — do NOT re-propose ({} older):",
            rejected.len()
        );
        let pointer = |n: usize| format!("- …and {n} more (see decisions.md)");
        blocks.push(Block::Yielding {
            rank: 4,
            preferred: DECISION_WINDOW_BUDGET + REJECTED_LEDGER_BUDGET,
            render: Box::new(move |budget: usize| {
                let reserve = if rejected.is_empty() {
                    0
                } else {
                    utf16_len(&ledger_header) + utf16_len(&pointer(rejected.len())) + 2
                };
                let window_room =
                    (DECISION_WINDOW_BUDGET as i64).min(budget as i64 - reserve as i64);
                let mut used = utf16_len(&window_header) as i64 + 1;
                let mut keep = 0;
                for entry in window_entries.iter().rev() {
                    if used + utf16_len(entry) as i64 + 1 > window_room {
                        break;
                    }
                    used += utf16_len(entry) as i64 + 1;
                    keep += 1;
                }
                let mut lines: Vec<String> = if keep > 0 {
                    let mut v = vec![window_header.clone()];
                    v.extend(
                        window_entries[window_entries.len() - keep..]
                            .iter()
                            .cloned(),
                    );
                    v
                } else {
                    Vec::new()
                };
                if keep == 0 {
                    used = 0;
                }
                if rejected.is_empty() || used + reserve as i64 > budget as i64 {
                    return lines;
                }
                let mut ledger = vec![ledger_header.clone()];
                let mut ledger_used = utf16_len(&ledger_header) as i64 + 1;
                let ledger_room = (REJECTED_LEDGER_BUDGET as i64).min(budget as i64 - used);
                let mut shown = 0;
                for (ordinal, d) in &rejected {
                    let entry = format!(
                        "- [D{ordinal}] {}",
                        minutiae_head(&d.over, REJECTED_OVER_LINE_BUDGET)
                    );
                    if ledger_used + utf16_len(&entry) as i64 + 1 + OVERFLOW_RESERVE as i64
                        > ledger_room
                    {
                        break;
                    }
                    ledger_used += utf16_len(&entry) as i64 + 1;
                    ledger.push(entry);
                    shown += 1;
                }
                if shown < rejected.len() {
                    ledger.push(pointer(rejected.len() - shown));
                }
                lines.extend(ledger);
                lines
            }),
            lines: Vec::new(),
        });
        blocks.push(Block::Fixed {
            lines: vec![String::new()],
            protected: false,
        });
    }

    // (9) Next handles, adjacency, the per-session tail, notices.
    if !state.decisions.is_empty() || !state.memories.is_empty() {
        fixed(
            &mut blocks,
            vec![
                format!(
                    "Next ids: D{} (decision), M{} (memory)",
                    state.decisions.len() + 1,
                    state.memories.len() + 1
                ),
                String::new(),
            ],
        );
    }
    let neighbours = &options.neighbours;
    if !neighbours.is_empty() {
        let named = &neighbours[..neighbours.len().min(MAX_NEIGHBOURS)];
        let decisions: u64 = neighbours.iter().map(|n| n.decisions).sum();
        let mut lines = vec![format!(
            "Adjacent records — {} across {} that have worked this one's files, densest first:",
            plural(decisions, "decision"),
            plural(neighbours.len() as u64, "other initiative")
        )];
        for n in named {
            lines.push(format!(
                "- {}",
                clip(
                    &format!(
                        "{} — {}, {}",
                        n.initiative,
                        plural(n.paths, "shared file"),
                        plural(n.decisions, "decision")
                    ),
                    NEIGHBOUR_LINE_BUDGET
                )
            ));
        }
        let rest = neighbours.len() - named.len();
        lines.push(format!(
            "{}Adjacency, not aboutness — offered as worth reading, never as a rule.",
            if rest > 0 {
                format!("…and {rest} more. ")
            } else {
                String::new()
            }
        ));
        lines.push(String::new());
        fixed(&mut blocks, lines);
    }
    let mut identity: Vec<String> = Vec::new();
    if let Some(line) = session_id_line(options.session_id.as_deref()) {
        identity.push(line);
    }
    if let Some(git) = &options.git {
        let sync = match &git.upstream {
            None => "no origin ref — never pushed".to_owned(),
            Some(_) if git.synced => format!("in sync with origin/{}", git.branch),
            Some(upstream) => format!(
                "differs from origin/{} ({upstream}) — unpushed work",
                git.branch
            ),
        };
        identity.push(format!(
            "Git: {}",
            clip(
                &format!("{} @ {} — {sync}", git.branch, git.head),
                GOAL_BUDGET
            )
        ));
    }
    if !identity.is_empty() {
        identity.push(String::new());
        fixed(&mut blocks, identity);
    }
    for notice in options.notices.iter().filter(|n| !js_trim(n).is_empty()) {
        fixed(&mut blocks, vec![notice.clone(), String::new()]);
    }

    // (10) Standing constraints LAST, most relevant first, then the other
    // records' rules in what this record's own left (D8) — protected.
    #[allow(clippy::cast_possible_wrap, reason = "line lengths are small")]
    let own_used: i64 = rules.iter().map(|l| utf16_len(l) as i64 + 1).sum();
    #[allow(clippy::cast_possible_wrap, reason = "budgets are small")]
    let elsewhere_budget = (REPO_RULES_BUDGET as i64).min(STANDING_LEDGER_BUDGET as i64 - own_used);
    let own_in_force: Vec<&DecisionState> = state
        .decisions
        .iter()
        .enumerate()
        .filter(|(i, _)| !retired.contains(&(i + 1)))
        .map(|(_, d)| d)
        .collect();
    let elsewhere = repo_rule_lines(
        &options.repo_rules,
        elsewhere_budget,
        &focus_terms,
        &own_in_force,
    );
    rendered_rule_lines.borrow_mut().clone_from(&elsewhere);
    if !rules.is_empty() || !elsewhere.is_empty() {
        let mut lines = rules.clone();
        lines.extend(elsewhere.iter().cloned());
        lines.push(String::new());
        blocks.push(Block::Fixed {
            lines,
            protected: true,
        });
    }
    // (11) Read-back, then the footer — protected.
    if !lane && (state.current.next_action.is_some() || !rules.is_empty() || !elsewhere.is_empty())
    {
        blocks.push(Block::Fixed {
            lines: vec![READ_BACK_LINE.to_owned(), String::new()],
            protected: true,
        });
    }
    blocks.push(Block::Fixed {
        lines: vec![FOOTER_LINE.to_owned()],
        protected: true,
    });

    let text = assemble(blocks, STATUS_CHAR_LIMIT);
    enforce_status_limit(&text)
}

/// A string field of the run surface, as `${s.x}` prints it (`undefined` when absent).
/// What `sofar status` knows about the record's other copies
/// (branch-visibility D1): the provenance of a union fold and the home dir
/// its worktree paths are tildified against. Default: no other copy.
#[derive(Debug, Clone, Copy, Default)]
pub struct CopiesView<'a> {
    pub provenance: Option<&'a crate::record_copies::RecordProvenance>,
    pub home: Option<&'a str>,
}

/// `renderFullStatus`: plain `sofar status`, uncapped, with the per-task tree.
/// `retire` is `retireEnabled()` (D25), read by the caller.
#[must_use]
#[allow(clippy::too_many_lines, reason = "a verbatim port of one template")]
pub fn render_full_status(
    state: &InitiativeState,
    retire: bool,
    liveness: Option<RunLiveness>,
    copies: &CopiesView<'_>,
) -> String {
    let mut lines: Vec<String> = Vec::new();
    lines.push(format!(
        "# {}",
        if state.slug.is_empty() {
            "(unnamed initiative)"
        } else {
            &state.slug
        }
    ));
    lines.push(String::new());
    if is_closed_initiative_status(&state.status) {
        let when = state
            .status_ts
            .as_ref()
            .map(|ts| format!(" {ts}"))
            .unwrap_or_default();
        let why = state
            .status_note
            .as_ref()
            .map(|n| format!(" — {n}"))
            .unwrap_or_default();
        let where_ = state
            .successor
            .as_ref()
            .map(|s| format!(" by {s}"))
            .unwrap_or_default();
        lines.push(format!("Status: {}{where_}{when}{why}", state.status));
        if !state.status_overrides.is_empty() {
            lines.push(format!(
                "Closed over {} finding(s):",
                state.status_overrides.len()
            ));
            for finding in &state.status_overrides {
                lines.push(format!("  - {finding}"));
            }
        }
    }
    lines.push(format!(
        "Goal: {}",
        if state.goal.is_empty() {
            "(none recorded)"
        } else {
            &state.goal
        }
    ));
    // The brief in full (r1-fixes 4.6): a terminal surface, uncapped.
    if !state.brief.is_empty() {
        lines.push(String::new());
        lines.push(BRIEF_HEADER.to_owned());
        lines.extend(state.brief.split('\n').map(str::to_owned));
    }

    let standing = standing_constraint_lines(&state.decisions, None, retire, None);
    if !standing.is_empty() {
        lines.push(String::new());
        lines.extend(standing);
    }

    lines.push(format!(
        "Progress: {} across {} phase(s)",
        progress_text(task_progress(&state.phases)),
        state.phases.len()
    ));
    // Other copies of the record hold events this checkout lacks
    // (branch-visibility D1): say what the figure above is made of.
    if let Some(p) = copies.provenance {
        lines.extend(crate::record_copies::render_provenance_block(
            p,
            copies.home,
        ));
    }
    lines.push(String::new());

    let stale_phases = stale_active_phases(state);
    let stale_names: Vec<&str> = stale_phases.iter().map(|p| p.name.as_str()).collect();

    if !state.phases.is_empty() {
        lines.push("Phases:".to_owned());
        for phase in &state.phases {
            lines.push(format!(
                "- {} {} {}",
                phase.name,
                phase_mark(phase, &stale_names),
                phase_fraction(task_progress([phase]))
            ));
            for task in &phase.tasks {
                lines.push(format!(
                    "  - {} {} {}",
                    task_mark(&task.status),
                    task.id,
                    task.title
                ));
            }
        }
        lines.push(String::new());
    }

    lines.push(format!(
        "Next action: {}",
        state
            .current
            .next_action
            .as_deref()
            .unwrap_or("(none recorded)")
    ));

    let parallel = overlapping_writebacks(state, None);
    if !parallel.is_empty() {
        lines.push(format!("⚠ Parallel write-backs ({}):", parallel.len()));
        for w in &parallel {
            lines.push(format!(
                "- {} ({}, ended {}): {}",
                w.session_id, w.tool, w.ended, w.next_action
            ));
        }
    }

    if let Some(blocked) = &state.current.blocked_on {
        lines.push(format!("Blocked on: {blocked}"));
    }

    let last = last_with_summary(&state.sessions);

    let drift = freshness_total(&state.freshness);
    let mut staleness: Vec<String> = Vec::new();
    if drift > 0
        && let Some(ts) = &state.freshness.last_writeback_ts
    {
        staleness.push(format!(
            "- next action may be stale: {drift} event{} since the last write-back ({ts}) — {}",
            if drift == 1 { "" } else { "s" },
            describe_freshness(&state.freshness.events_since_writeback)
        ));
    }
    for sp in &stale_phases {
        staleness.push(format!(
            "- phase \"{}\": all {} tasks done but still {} — emit phase_status_changed to mark it done",
            sp.name, sp.tasks_done, sp.status
        ));
    }
    if let Some(last) = last
        && let Some(summary) = &last.summary
        && clip_detect(summary, SESSION_SUMMARY_BUDGET).1
    {
        staleness.push(format!(
            "- last write-back summary exceeds the SessionStart budget ({SESSION_SUMMARY_BUDGET} chars) and is clipped there — full text in sessions/{}.md",
            last.id
        ));
    }
    if !staleness.is_empty() {
        lines.push(String::new());
        lines.push("⚠ Staleness:".to_owned());
        lines.extend(staleness);
    }

    if !state.freshness.notes.is_empty() {
        lines.push(String::new());
        let label = if state.freshness.last_writeback_ts.is_some() {
            "Notes since write-back"
        } else {
            "Notes"
        };
        lines.push(format!("{label} ({}):", state.freshness.notes.len()));
        for n in &state.freshness.notes {
            lines.push(format!("- {} {}", n.ts, one_line(&n.text)));
        }
    }

    let conflicts = open_session_file_conflicts(state, None);
    if !conflicts.is_empty() {
        lines.push(String::new());
        lines.push(format!(
            "⚠ Concurrent edits — files touched by multiple open sessions ({}):",
            conflicts.len()
        ));
        for c in &conflicts {
            lines.push(format!("- {} (sessions {})", c.path, c.sessions.join(", ")));
        }
    }

    if let Some(last) = last {
        lines.push(String::new());
        lines.push(format!(
            "Last session ({}, ended {}):",
            last.tool,
            last.ended.as_deref().unwrap_or("?")
        ));
        lines.push(format!(
            "  {}",
            last.summary.as_deref().expect("has summary")
        ));
    }

    if !state.runs.is_empty() {
        lines.push(String::new());
        lines.push(format!(
            "Driven ({}):",
            plural(state.runs.len() as u64, "run")
        ));
        let latest = state.runs.len() - 1;
        for (i, run) in state.runs.iter().enumerate() {
            let liveness = if i == latest { liveness } else { None };
            lines.push(format!("- {}", describe_run(run, liveness)));
            lines.extend(run_detail_lines(run));
        }
    }

    if !state.files_touched.is_empty() {
        lines.push(String::new());
        lines.push(format!("Files touched ({}):", state.files_touched.len()));
        for file in &state.files_touched {
            lines.push(format!("- {file}"));
        }
    }

    let joined = lines.join("\n");
    format!("{}\n", joined.trim_end_matches('\n'))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fold::empty_state;

    #[test]
    fn the_cap_cuts_to_fit_with_the_marker_inside() {
        let text = "x".repeat(10_001);
        let capped = enforce_status_limit(&text);
        assert_eq!(utf16_len(&capped), STATUS_CHAR_LIMIT);
        assert!(capped.ends_with(&format!("\n{STATUS_TRUNCATION_MARKER}\n")));
        assert_eq!(enforce_status_limit("short"), "short");
        // Emoji count two units each; the cut may split one.
        let emoji = "\u{1F600}".repeat(5_001);
        let capped = enforce_status_limit(&emoji);
        assert_eq!(utf16_len(&capped), STATUS_CHAR_LIMIT);
    }

    #[test]
    fn real_alternative_detection_is_ascii_case_insensitive() {
        assert!(has_real_alternative("keep it"));
        assert!(!has_real_alternative("  "));
        assert!(!has_real_alternative("(no alternative recorded)"));
        assert!(!has_real_alternative("( NONE considered)"));
        assert!(!has_real_alternative("(\u{00A0}No Alternative"));
        assert!(has_real_alternative("(nothing)"));
        assert!(has_real_alternative("(\u{017F}one"));
    }

    #[test]
    fn empty_record_renders_the_bare_block() {
        let mut state = empty_state();
        state.slug = "demo".into();
        let out = render_status(&state, &StatusOptions::default());
        assert_eq!(
            out,
            "# Sofar status: demo\n\nGoal: (none recorded)\n\n(generated by sofar — full detail in plan.md, decisions.md, sessions/)\n"
        );
        let full = render_full_status(&state, true, None, &CopiesView::default());
        assert_eq!(
            full,
            "# demo\n\nGoal: (none recorded)\nProgress: 0/0 tasks done (0%) across 0 phase(s)\n\nNext action: (none recorded)\n"
        );
    }

    #[test]
    fn session_line_trims_and_clips() {
        assert_eq!(session_id_line(None), None);
        assert_eq!(session_id_line(Some(" \u{FEFF} ")), None);
        assert_eq!(
            session_id_line(Some(" abc ")),
            Some("Session: abc — adopted on Claude Code; else pass to sofar_start_session.".into())
        );
    }
}
