// GENERATED by `cargo xtask schema` from crates/sofar-schema/schema/events.schema.json,
// itself emitted from packages/schema/src/events.ts by `npm run schema:emit`.
// Do not edit: change the TypeScript, regenerate, review the diff (rust-core D1).

#[doc = "Words added to the plan's brief without resending it (r3-fixes 2.9, D6). The L36 fix keeps every session's operator words in the brief, so a plan_updated that restated it grew with the chain: round 3 resent 0.70–0.81M chars of brief a chain, 50–60% of events.jsonl. The fold appends `text` to the brief after a blank line; plan_updated's `brief` stays the full restatement. A write path that keeps a captured prompt by id fills `text` with the prompt, verbatim and scrubbed — the event itself carries words only."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct BriefAppendedPayload {
    pub text: ::std::string::String,
}
#[doc = "`CommandRunPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct CommandRunPayload {
    pub cmd: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub exit: ::std::option::Option<i64>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub ok: ::std::option::Option<bool>,
}
#[doc = "`CorrectionPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct CorrectionPayload {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub reason: ::std::option::Option<::std::string::String>,
    #[serde(rename = "ref")]
    pub ref_: ::std::string::String,
}
#[doc = "The command that checks a decision still holds, and the fix to show when it does not (D9)."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DecisionCheck {
    #[doc = "≤ CHECK_CMD_MAX chars; run from the repo root; exit 0 = the decision holds."]
    pub cmd: ::std::string::String,
    #[doc = "The remediation a failure shows, ≤ CHECK_HINT_MAX chars; absent, the rule and its quote stand in."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub hint: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub timeout_ms: ::std::option::Option<i64>,
}
#[doc = "A decision's supersession, answered after it was filed (r3-fixes 2.5, D15): `sofar link D<n> <D<m>|none>`. `supersedes` absent means \"checked, it replaces nothing\". The handles are as the writer read them; the ids, stamped by the writer, decide — a merge renumbers handles, never ids. The fold clears the decision's pending link and retires the target under D25's law: a rule is replaced only by a rule, and only an earlier decision can be replaced."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DecisionLinkedPayload {
    pub decision: ::std::string::String,
    pub decision_id: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub supersedes: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub supersedes_id: ::std::option::Option<::std::string::String>,
}
#[doc = "`rule` (drift-hardening D1): optional standing-constraint clause — one short imperative every future session must obey. Its presence is what makes a decision a standing constraint; there is no separate flag. Render contract: verbatim on every surface, never clipped, never aged out — the C-abl ablation showed decisions are the load-bearing resume field, and clipped normative text is how dead ends recur."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct DecisionLoggedPayload {
    pub because: ::std::string::String,
    #[doc = "`check` (memory-lead 2.3, D9): the executable half of the SAME clause — a shell command whose exit 0 means the decision holds. Valid only alongside `rule`, like `guard`: a failure has to cite the clause it enforces. It is text an agent wrote into a shared record, so nothing runs it until the operator approved that exact command on their clone, or, under `sofar drive`, the run's permission surface covers it. It WARNS everywhere, and blocks only at drive's task acceptance and, opted in, at pre-commit."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub check: ::std::option::Option<DecisionCheck>,
    pub chose: ::std::string::String,
    #[doc = "`guard` (drift-hardening D3): the mechanical half of the SAME clause — a `path:`/`cmd:` glob list (src/guards.ts) the fold matches against file_touched / command_run events logged after this decision. Valid only alongside `rule`: a guard with no clause has nothing to cite when it fires, and what it produces is a WARNING that never changes an exit code."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub guard: ::std::option::Option<::std::string::String>,
    #[doc = "`link_candidates` (r3-fixes 2.5, D15): event ids of up to three earlier, in-force, rule-carrying decisions this one may replace, stamped by the writer when a rule arrives naming no `supersedes` — agents never pass it. Its presence marks the link PENDING until a decision_linked answers it: round 3 left 14 of 48 changed rules unlinked, each old rule still in force beside its replacement, because nothing asked. Only alongside `rule`, never alongside `supersedes`."]
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub link_candidates: ::std::vec::Vec<::std::string::String>,
    pub over: ::std::string::String,
    #[doc = "`quote` (memory-lead 1.2, D2): the operator's own words the rule came from, copied exactly — ≤ RULE_QUOTE_MAX chars, valid only alongside `rule`. The rule is the agent's restatement; the quote is its source, and every surface that renders the rule renders the quote beside it, flagging the status codes, paths and values the rule adds (engine core/rule-fidelity.ts). Round 1 lost a test to a rule that added \"with 4xx\" to an operator's \"Reject anything else\"."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub quote: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub rule: ::std::option::Option<::std::string::String>,
    #[doc = "`supersedes` (r1-fixes 3.2, D25): the bare handle `D<n>` of an EARLIER decision in the SAME record this one replaces. The fold resolves it from the log alone and marks the target `superseded_by` this decision's ordinal; the digest then stops rendering the target. Per-record like the ordinals themselves. A rule-carrying target is retired ONLY by a rule-carrying superseder — standing rules never age out, they are only ever replaced by a new rule that names them; any other reference is recorded but inert (forward, self, rule mismatch)."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub supersedes: ::std::option::Option<::std::string::String>,
    #[doc = "`supersedes_held` (r3-fixes 2.6, D18): the `D<n>` the writer was given as what this decision replaces, HELD instead of taken — stamped by the writer, agents never pass it. Two keys must agree before a target retires: the handle typed, and what the decision's own words match. When the named target shares little with them while an in-force decision it could retire shares far more, or the target is already replaced or no longer in force, the handle moves here, `link_candidates` carries the named target's id first, then the better matches, and the link is pending like any other: the target stays in force until a decision_linked answers. Round 3 retired the wrong entry twice in 3 reps, one of them a guarded rule. Only alongside `link_candidates`, never alongside `supersedes`."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub supersedes_held: ::std::option::Option<::std::string::String>,
    #[doc = "`supersedes_id` (memory-lead 2.8, D12): the event id of the decision `supersedes` named when it was written, stamped by the writer from its own fold — agents never pass it. `D<n>` is a position in id order, so a union merge of branches that both logged decisions moves it; the id does not. When present the fold resolves by it alone. Only alongside `supersedes`."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub supersedes_id: ::std::option::Option<::std::string::String>,
    #[doc = "`until` (r1-fixes 3.2, D25): the id of a task in this record. The decision is in force until that task RESOLVES (done or dropped, as replayed) and then leaves the digest — validity derives from recorded events, never from a clock. REJECTED alongside `rule`: a standing constraint never ages out. An id the plan never names never retires."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub until: ::std::option::Option<::std::string::String>,
}
#[doc = "Mechanical outcome fields (self-improve D2): OPTIONAL, additive, and the ONLY outcome facts the durable record carries. `ok` is what the host said about the call — PostToolUse fires only on success, PostToolUseFailure only on failure — and `exit` is the process status when the host supplies one as a number. Absent means UNKNOWN (an engine or host that predates capture), never success. Everything richer — error text, output, timing — is a diagnostics row (src/diagnostics.ts), never a payload field."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct FileTouchedPayload {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub ok: ::std::option::Option<bool>,
    pub op: ::std::string::String,
    pub path: ::std::string::String,
}
#[doc = "`HandoffPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct HandoffPayload {
    #[doc = "How the agent process ended, when that is worth knowing (r1-fixes 1.6, D9): the exit code or signal, a spawn error, the last stderr line. Set on stalls and on any unclean exit; never consulted for `reason`, which the driver reads from the fold alone (session-driver D5)."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub detail: ::std::option::Option<::std::string::String>,
    pub reason: HandoffReason,
    pub run: ::std::string::String,
    #[doc = "The session that just ended — registered here by its own session_started."]
    pub session_id: ::std::string::String,
    #[doc = "Task the session was working, when the driver knows it."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub task: ::std::option::Option<::std::string::String>,
    #[doc = "Context tokens the session held when it ended, when the adapter could report them."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub tokens: ::std::option::Option<i64>,
}
#[doc = "`HandoffReason`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum HandoffReason {
    #[serde(rename = "task_done")]
    TaskDone,
    #[serde(rename = "threshold")]
    Threshold,
    #[serde(rename = "stall")]
    Stall,
    #[serde(rename = "needs_user")]
    NeedsUser,
    #[serde(rename = "verify_failed")]
    VerifyFailed,
}
impl ::std::fmt::Display for HandoffReason {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::TaskDone => f.write_str("task_done"),
            Self::Threshold => f.write_str("threshold"),
            Self::Stall => f.write_str("stall"),
            Self::NeedsUser => f.write_str("needs_user"),
            Self::VerifyFailed => f.write_str("verify_failed"),
        }
    }
}
impl ::std::str::FromStr for HandoffReason {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "task_done" => Ok(Self::TaskDone),
            "threshold" => Ok(Self::Threshold),
            "stall" => Ok(Self::Stall),
            "needs_user" => Ok(Self::NeedsUser),
            "verify_failed" => Ok(Self::VerifyFailed),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for HandoffReason {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for HandoffReason {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`InitiativeCreatedPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct InitiativeCreatedPayload {
    pub goal: ::std::string::String,
    pub slug: ::std::string::String,
}
#[doc = "`InitiativeStatus`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum InitiativeStatus {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "done")]
    Done,
    #[serde(rename = "dropped")]
    Dropped,
    #[serde(rename = "superseded")]
    Superseded,
}
impl ::std::fmt::Display for InitiativeStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Active => f.write_str("active"),
            Self::Done => f.write_str("done"),
            Self::Dropped => f.write_str("dropped"),
            Self::Superseded => f.write_str("superseded"),
        }
    }
}
impl ::std::str::FromStr for InitiativeStatus {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "active" => Ok(Self::Active),
            "done" => Ok(Self::Done),
            "dropped" => Ok(Self::Dropped),
            "superseded" => Ok(Self::Superseded),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for InitiativeStatus {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for InitiativeStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "The initiative's own status changed. `note` is the reason, and it is REQUIRED for `dropped` (task-drop-state D3): a whole initiative abandoned with nothing said reads as forgotten rather than decided, and unlike a dropped task there is no surviving sibling work to infer the reason from.\n\nReopening is just another event with status `active` — history stays append-only, so a closed initiative is never a dead end in the log.\n\n`overrides` (commit-attribution 5.2) is what the close-time audit found still outstanding, recorded because the close went ahead anyway. It is the whole mechanism: a hard refusal on a solo tool grows a `--force` and the flag becomes the habit, while \"closed with 3 tasks outstanding, overridden\" rendered in the digest forever is a sentence its author has to live beside. Absent means the audit found nothing — never that it was skipped."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct InitiativeStatusChangedPayload {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub overrides: ::std::vec::Vec<::std::string::String>,
    pub status: InitiativeStatus,
    #[doc = "The slug this record continues in. REQUIRED for `superseded` and rejected on every other status — a successor on a `done` record is a contradiction the validator refuses rather than one the fold has to interpret. Recorded ONLY here, on the predecessor (initiative-supersession D1): the successor's side is derived at read time, never written on the successor."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub successor: ::std::option::Option<::std::string::String>,
}
#[doc = "`JudgementAnswer`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
#[serde(tag = "type")]
pub enum JudgementAnswer {
    #[serde(rename = "noul")]
    Noul { noul: f64 },
    #[serde(rename = "choice")]
    Choice {
        choice: ::std::string::String,
        confidence: f64,
        probabilities: ::std::collections::HashMap<::std::string::String, f64>,
    },
    #[serde(rename = "score")]
    Score {
        confidence: f64,
        probabilities: ::std::collections::HashMap<::std::string::String, f64>,
        score: f64,
    },
}
#[doc = "`JudgementRecordedPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct JudgementRecordedPayload {
    #[doc = "What `subject` was judged AGAINST, for a relevance judgement (typed-judge D10): `task:<id>` (a task of the envelope's initiative) or `file:<repo-relative path>`. Absent for a judgement about the subject alone."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub about: ::std::option::Option<::std::string::String>,
    pub answer: JudgementAnswer,
    #[doc = "Exact model version (never an alias), or `deterministic`."]
    pub model: ::std::string::String,
    #[doc = "Who ran the judge: `sofar-cloud`, `deterministic`, `agent`, …"]
    pub producer: ::std::string::String,
    #[doc = "The question id, as the seam names it (`relevance`, `progress`, …)."]
    pub question: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub state_hash: ::std::option::Option<::std::string::String>,
    #[doc = "What it is about: an event id, a task id of this initiative, or a record handle qualified per the citation grammar — a bare `D12` is the envelope's own initiative, anything else `<slug> D12` / `<slug> M3` (typed-judge D10)."]
    pub subject: ::std::string::String,
}
#[doc = "`KnownEventPayloads`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct KnownEventPayloads {
    pub brief_appended: BriefAppendedPayload,
    pub command_run: CommandRunPayload,
    pub correction: CorrectionPayload,
    pub decision_linked: DecisionLinkedPayload,
    pub decision_logged: DecisionLoggedPayload,
    pub file_touched: FileTouchedPayload,
    pub handoff: HandoffPayload,
    pub initiative_created: InitiativeCreatedPayload,
    pub initiative_status_changed: InitiativeStatusChangedPayload,
    pub judgement_recorded: JudgementRecordedPayload,
    pub memory_promoted: MemoryPromotedPayload,
    pub note_added: NoteAddedPayload,
    pub phase_added: PhaseAddedPayload,
    pub phase_status_changed: PhaseStatusChangedPayload,
    pub plan_updated: PlanUpdatedPayload,
    pub review_recorded: ReviewRecordedPayload,
    pub run_adopted: RunAdoptedPayload,
    pub run_started: RunStartedPayload,
    pub run_stop_requested: RunStopRequestedPayload,
    pub run_stopped: RunStoppedPayload,
    pub session_closed: SessionClosedPayload,
    pub session_ended: SessionEndedPayload,
    pub session_started: SessionStartedPayload,
    pub suggestion_approved: SuggestionTransitionPayload,
    pub suggestion_proposed: SuggestionProposedPayload,
    pub suggestion_rejected: SuggestionTransitionPayload,
    pub suggestion_reverted: SuggestionTransitionPayload,
    pub task_added: TaskAddedPayload,
    pub task_status_changed: TaskStatusChangedPayload,
    pub verification_recorded: VerificationRecordedPayload,
}
#[doc = "A fact its author declares repo memory — operational knowledge that is not a decision (a release command, a failure mode) and so can never be observed as repo-general from citation behaviour, because nothing derives a fact that was never written down (repo-memory-capture D1)."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct MemoryPromotedPayload {
    #[doc = "Where the words came from when they are not the author's own (memory-lead 2.4, D13/D14): `claude-memory:<file>@<16 hex>` — a Claude Code auto-memory topic file the operator approved importing, and the first 16 hex of that file's sha256 at import. Every surface marks such a memory as native memory's words; a changed file is a new digest, so an import is offered again as an update."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub origin: ::std::option::Option<::std::string::String>,
    #[doc = "The QUALIFIED handle `<slug> M<n>` of the memory this one replaces (r1-fixes 1.5, D8). Facts go stale; the record is append-only, so the replacement is a new promotion that names the old one, and readers (memory.md, doctor's repo-memory axis) retire the old handle."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub supersedes: ::std::option::Option<::std::string::String>,
    #[doc = "The event id of the memory `supersedes` named when it was written (memory-lead 2.8, D12), stamped by the writer — `M<n>` moves on a merge, the id does not. Only alongside `supersedes`."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub supersedes_id: ::std::option::Option<::std::string::String>,
    pub text: ::std::string::String,
}
#[doc = "`NoteAddedPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct NoteAddedPayload {
    pub text: ::std::string::String,
}
#[doc = "One phase added to a live plan without resending it (phase-lifecycle 7.1, D10): plan_updated's full replace was the only way in, so adding a phase meant restating every task. `after` places it behind the phase of that exact name; absent, or naming no phase, it goes last. `status` defaults to `pending`; `note` is the same reason-for-status phase_status_changed carries."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PhaseAddedPayload {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub after: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
    pub phase: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub status: ::std::option::Option<PhaseStatus>,
}
#[doc = "`PhaseStatus`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum PhaseStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "done")]
    Done,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "dropped")]
    Dropped,
}
impl ::std::fmt::Display for PhaseStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Pending => f.write_str("pending"),
            Self::Active => f.write_str("active"),
            Self::Done => f.write_str("done"),
            Self::Blocked => f.write_str("blocked"),
            Self::Dropped => f.write_str("dropped"),
        }
    }
}
impl ::std::str::FromStr for PhaseStatus {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "pending" => Ok(Self::Pending),
            "active" => Ok(Self::Active),
            "done" => Ok(Self::Done),
            "blocked" => Ok(Self::Blocked),
            "dropped" => Ok(Self::Dropped),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for PhaseStatus {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for PhaseStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`note` (phase-lifecycle 2.1) is the same field task_status_changed carries, one level up, and required for `dropped` for the same reason: a phase abandoned without a stated reason is indistinguishable from one quietly forgotten, and nothing else in the record explains it."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PhaseStatusChangedPayload {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
    pub phase: ::std::string::String,
    pub status: PhaseStatus,
}
#[doc = "`PlanPhaseInput`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PlanPhaseInput {
    pub name: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub status: ::std::option::Option<PhaseStatus>,
    pub tasks: ::std::vec::Vec<PlanTaskInput>,
}
#[doc = "Full plan structure carried by plan_updated (full replace, SPEC §MCP tools)."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PlanStructure {
    #[doc = "The operator's own words the plan was made from — a roadmap, a spec, a list of steps — VERBATIM (r1-fixes 4.6, L36). Kept when a later replace omits it, like goal: tasks are the agent's summary of it and lose words, and finishing every task does not finish the brief."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub brief: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub goal: ::std::option::Option<::std::string::String>,
    pub phases: ::std::vec::Vec<PlanPhaseInput>,
}
#[doc = "`PlanTaskInput`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PlanTaskInput {
    pub id: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub route: ::std::option::Option<TaskRoute>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub status: ::std::option::Option<TaskStatus>,
    pub title: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub verify: ::std::option::Option<TaskVerify>,
    #[doc = "Declared links (linked-context 2.1, SPEC §Links): canonical qualified handles."]
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub waits_on: ::std::vec::Vec<::std::string::String>,
}
#[doc = "`PlanUpdatedPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct PlanUpdatedPayload {
    pub plan: PlanStructure,
}
#[doc = "A review that was actually performed (commit-attribution 4.4).\n\n`watermark` is the load-bearing field, not `verdict`. It is the sha the review read through, and it is what makes the NEXT review's range computable — watermark..HEAD filtered to this initiative's attributed commits (D9). Without it a range could only be derived from task timestamps, which is the time-window guess record-integrity D6 rejected. That is why a review is an EVENT and could never have been a note.\n\n`findings` are the ones that survived, one line each. An empty list with verdict `pass` is a legitimate outcome; an empty list with verdict `findings` is not, and validation rejects it — a review that reports findings must say what they were, or it is a rubber stamp wearing the wrong hat."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct ReviewRecordedPayload {
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub findings: ::std::vec::Vec<::std::string::String>,
    #[doc = "Phase name for a `phase` review; absent for `final`."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub phase: ::std::option::Option<::std::string::String>,
    pub scope: ReviewScope,
    pub verdict: ReviewVerdict,
    #[doc = "Sha read through; omitted only when the range was empty."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub watermark: ::std::option::Option<::std::string::String>,
}
#[doc = "`ReviewScope`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum ReviewScope {
    #[serde(rename = "phase")]
    Phase,
    #[serde(rename = "final")]
    Final,
}
impl ::std::fmt::Display for ReviewScope {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Phase => f.write_str("phase"),
            Self::Final => f.write_str("final"),
        }
    }
}
impl ::std::str::FromStr for ReviewScope {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "phase" => Ok(Self::Phase),
            "final" => Ok(Self::Final),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ReviewScope {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ReviewScope {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`ReviewVerdict`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum ReviewVerdict {
    #[serde(rename = "pass")]
    Pass,
    #[serde(rename = "findings")]
    Findings,
    #[serde(rename = "blocked")]
    Blocked,
}
impl ::std::fmt::Display for ReviewVerdict {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Pass => f.write_str("pass"),
            Self::Findings => f.write_str("findings"),
            Self::Blocked => f.write_str("blocked"),
        }
    }
}
impl ::std::str::FromStr for ReviewVerdict {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "pass" => Ok(Self::Pass),
            "findings" => Ok(Self::Findings),
            "blocked" => Ok(Self::Blocked),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for ReviewVerdict {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for ReviewVerdict {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "A driver took over a run that has no stop (drive-visibility 2.2): `sofar drive --resume` appends one before its first launch, at one more than the run's highest epoch — `run_started` is epoch 1, so an adoption is never below 2. The fencing token for a record that syncs: the fold's owner is the highest epoch (the first-sorting id on a tie), and a driver that finds it is no longer the owner steps down. One event per takeover, never a heartbeat."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct RunAdoptedPayload {
    pub epoch: i64,
    pub run: ::std::string::String,
}
#[doc = "`RunPolicy`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum RunPolicy {
    #[serde(rename = "task")]
    Task,
    #[serde(rename = "threshold")]
    Threshold,
}
impl ::std::fmt::Display for RunPolicy {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Task => f.write_str("task"),
            Self::Threshold => f.write_str("threshold"),
        }
    }
}
impl ::std::str::FromStr for RunPolicy {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "task" => Ok(Self::Task),
            "threshold" => Ok(Self::Threshold),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for RunPolicy {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for RunPolicy {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`RunStartedPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct RunStartedPayload {
    #[doc = "Adapter name, e.g. `claude-code`: which headless agent the run launches."]
    pub adapter: ::std::string::String,
    #[doc = "Tokens the session's context window holds — the DENOMINATOR `threshold_pct` is a percentage of, and REQUIRED for `threshold` for the same reason the percentage is: 80% of 200k and 80% of 1M are different runs, so a record carrying only the percentage cannot say what the last driver actually nudged at. Sofar never infers it from the model name — a model table it cannot keep true would mis-time every handoff silently — so the operator states it and the record keeps it (session-driver 2.3)."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub context_window: ::std::option::Option<i64>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub max_sessions: ::std::option::Option<i64>,
    pub policy: RunPolicy,
    #[doc = "Run id minted by the driver (a ulid) — the key every handoff and the stop cite."]
    pub run: ::std::string::String,
    #[doc = "The permission surface every session in the run was launched under (session-driver 2.4, D8) — what the driver PINNED, never what the session could ultimately do: the agent's settings file is one source among the operator's own and allow rules union across them. Absent on a run whose adapter pins nothing. `model`/`effort` are recorded here so a reader can tell a run that pinned them from one that left them to whatever the operator's mutable config said that day."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub surface: ::std::option::Option<RunSurface>,
    #[doc = "Context percentage at which a session is told to finish and hand off; REQUIRED for `threshold`."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub threshold_pct: ::std::option::Option<i64>,
    #[doc = "The run's default acceptance command (r1-fixes 3.1, D19): `--verify`, applied to every task that carries no `verify` of its own. Operator- stated, so it always runs; recorded so a resumed run keeps it."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub verify: ::std::option::Option<::std::string::String>,
}
#[doc = "`RunStopReason`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum RunStopReason {
    #[serde(rename = "closed")]
    Closed,
    #[serde(rename = "needs_user")]
    NeedsUser,
    #[serde(rename = "stall")]
    Stall,
    #[serde(rename = "cost_cap")]
    CostCap,
    #[serde(rename = "max_sessions")]
    MaxSessions,
    #[serde(rename = "interrupted")]
    Interrupted,
    #[serde(rename = "error")]
    Error,
}
impl ::std::fmt::Display for RunStopReason {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Closed => f.write_str("closed"),
            Self::NeedsUser => f.write_str("needs_user"),
            Self::Stall => f.write_str("stall"),
            Self::CostCap => f.write_str("cost_cap"),
            Self::MaxSessions => f.write_str("max_sessions"),
            Self::Interrupted => f.write_str("interrupted"),
            Self::Error => f.write_str("error"),
        }
    }
}
impl ::std::str::FromStr for RunStopReason {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "closed" => Ok(Self::Closed),
            "needs_user" => Ok(Self::NeedsUser),
            "stall" => Ok(Self::Stall),
            "cost_cap" => Ok(Self::CostCap),
            "max_sessions" => Ok(Self::MaxSessions),
            "interrupted" => Ok(Self::Interrupted),
            "error" => Ok(Self::Error),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for RunStopReason {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for RunStopReason {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "An operator asking the driver of `run` to end it from OUTSIDE the driver (in-session-drive D2) — `sofar drive --stop`, for a detached driver no ^C can reach. A request, never a stop: only the driver writes `run_stopped`, after reading the handoff of the session it signalled."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct RunStopRequestedPayload {
    pub run: ::std::string::String,
}
#[doc = "`RunStoppedPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct RunStoppedPayload {
    #[doc = "What happened; REQUIRED for `error` — a run that died unexplained is one nobody can resume."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
    pub reason: RunStopReason,
    pub run: ::std::string::String,
}
#[doc = "What `run_started.surface` carries; the driver's own type is engine-side."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct RunSurface {
    pub allow: ::std::vec::Vec<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub deny: ::std::vec::Vec<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub effort: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub model: ::std::option::Option<::std::string::String>,
    pub permission_mode: ::std::string::String,
}
#[doc = "Mechanical session close (SessionEnd hook fallback). Deliberately has no summary/next_action: those belong to session_ended (the write-back) and a mechanical close must never clobber them during fold."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct SessionClosedPayload {
    pub reason: ::std::string::String,
}
#[doc = "`SessionEndedPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct SessionEndedPayload {
    pub next_action: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub session_id: ::std::option::Option<::std::string::String>,
    pub summary: ::std::string::String,
}
#[doc = "`rehome` (binding-follows-session 3.1, D5): this is a DELIBERATE re-home — sofar_start_session naming this initiative for a session already registered here but homed elsewhere since. The session's home is the log holding its LATEST session_started, so without a new line a session could never return to a record it had left. The fold accepts the repeat silently; a repeat WITHOUT it is still the racing double-registration it warns about."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct SessionStartedPayload {
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub model: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub rehome: ::std::option::Option<bool>,
    pub tool: ::std::string::String,
}
#[doc = "A LOSS ROW proposed from a trusted detector — never a cause, never a fix (self-improve 2.3). `candidate` is sha256 over {version, signal, scope, sorted evidence}, so new evidence is a new candidate and approval binds to the exact one."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct SuggestionProposedPayload {
    pub candidate: ::std::string::String,
    pub count: i64,
    #[doc = "Highest event id the deriving report read. Recorded, never hashed."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub cutoff: ::std::option::Option<::std::string::String>,
    pub detector_version: i64,
    pub engine: ::std::string::String,
    #[doc = "Event ids (or `row:` hashes) the detector cited — the whole set the hash covers."]
    pub evidence: ::std::vec::Vec<::std::string::String>,
    pub signal: ::std::string::String,
    pub trust: SuggestionTrust,
}
#[doc = "approve / reject / revert: append-only transitions on one candidate."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct SuggestionTransitionPayload {
    pub candidate: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub reason: ::std::option::Option<::std::string::String>,
}
#[doc = "What the 2.2 protocol measured about the detector behind a suggestion (self-improve 2.3): a reader sees how often this signal is right without leaving the row. Every field is a measurement, never an estimate."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct SuggestionTrust {
    #[doc = "Findings judged on held-out splits — the n behind the precision."]
    pub judged: i64,
    pub precision: f64,
    #[doc = "Event id of the protocol decision the numbers were produced under."]
    pub protocol: ::std::string::String,
    pub recall: f64,
    #[doc = "Event id of the decision carrying the verdict."]
    pub verdict: ::std::string::String,
}
#[doc = "`waits_on` (linked-context 2.1, SPEC §Links) is the task's DECLARED link set, additive and optional like command_run's `ok`/`exit`: an old reader ignores it. Absent leaves the set unchanged, present replaces it, `[]` clears it. Stored entries are always canonical qualified handles (WAITS_ON_HANDLE_RE) — write surfaces qualify a bare `D<n>`, `T<n>` or `<n>.<n>` to the home slug before the append, so the log never holds one."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct TaskAddedPayload {
    pub id: ::std::string::String,
    pub phase: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub status: ::std::option::Option<TaskStatus>,
    pub title: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub verify: ::std::option::Option<TaskVerify>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub waits_on: ::std::vec::Vec<::std::string::String>,
}
#[doc = "Where a task wants to be run (session-driver 3.2, D10). Hints, not orders: anything the RUN states — the model/effort `run_started.surface` recorded, or the driver's own flags — wins over them, because a run whose second half ran a different model than its record names is two runs wearing one id. What the run leaves open, the task fills.\n\n`agent` names an ADAPTER (`claude-code`, `codex`), and it is the one field the driver cannot honour halfway: a run that cannot reach the named agent, or whose policy that agent cannot run, refuses to start rather than falling back to the default one.\n\nNothing else records the route: the plan carries the hint and the launched session's own `session_started` carries the tool and model it actually ran, so a third copy on the handoff would be the one that goes stale (D3)."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, Default, PartialEq)]
pub struct TaskRoute {
    #[doc = "Adapter name the driver must launch this task with."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub agent: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub effort: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub model: ::std::option::Option<::std::string::String>,
}
#[doc = "`TaskStatus`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum TaskStatus {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "done")]
    Done,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "dropped")]
    Dropped,
}
impl ::std::fmt::Display for TaskStatus {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Pending => f.write_str("pending"),
            Self::Active => f.write_str("active"),
            Self::Done => f.write_str("done"),
            Self::Blocked => f.write_str("blocked"),
            Self::Dropped => f.write_str("dropped"),
        }
    }
}
impl ::std::str::FromStr for TaskStatus {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "pending" => Ok(Self::Pending),
            "active" => Ok(Self::Active),
            "done" => Ok(Self::Done),
            "blocked" => Ok(Self::Blocked),
            "dropped" => Ok(Self::Dropped),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for TaskStatus {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for TaskStatus {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`TaskStatusChangedPayload`"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct TaskStatusChangedPayload {
    pub id: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub note: ::std::option::Option<::std::string::String>,
    pub status: TaskStatus,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub waits_on: ::std::vec::Vec<::std::string::String>,
}
#[doc = "The task's acceptance command (r1-fixes 3.1, D19): what `sofar drive` runs before it accepts the task as done. A shell command line, run in `cwd` relative to the launch directory (default the launch directory itself), killed after `timeout_ms`. The plan carries it like a route, and like a route it survives only as long as a full-replace plan restates it. An agent can write a plan, so the driver runs a plan-level command ONLY when it falls inside the run's recorded permission surface (D19) — the operator's `--verify` is the other, always-approved source."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct TaskVerify {
    pub cmd: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub cwd: ::std::option::Option<::std::string::String>,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub timeout_ms: ::std::option::Option<i64>,
}
#[doc = "The driver ran a task's acceptance command (r1-fixes 3.1, D19) — the record of WHAT was checked, on WHICH tree, and how it ended. Written by the driver before it accepts a `task_done`, and again on every retry; the fold keeps each task's latest. A pass counts only while `checked` still names the current tree and `command` is unchanged — the driver re-fingerprints before trusting one. Diagnostics are a bounded, redacted tail of the command's output (D9's precedent for driver diagnostics on the record)."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct VerificationRecordedPayload {
    pub attempt: i64,
    pub checked: VerificationRecordedPayloadChecked,
    pub command: ::std::string::String,
    #[doc = "Relative to the launch directory; `.` for the launch directory itself."]
    pub cwd: ::std::string::String,
    #[doc = "The decision whose `check` this was, as `<slug> D<n>` (memory-lead 2.3, D9). Absent: the task's own acceptance command. The fold keeps the two apart, so a check never displaces the task's verify pass."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub decision: ::std::option::Option<::std::string::String>,
    #[doc = "≤1,024 chars: ANSI-stripped, redacted tail of stdout and stderr."]
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub diagnostics: ::std::option::Option<::std::string::String>,
    pub duration_ms: i64,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub exit_code: ::std::option::Option<i64>,
    pub result: VerificationResult,
    pub run: ::std::string::String,
    #[serde(skip_serializing_if = "::std::option::Option::is_none")]
    pub signal: ::std::option::Option<::std::string::String>,
    pub task: ::std::string::String,
    pub timeout_ms: i64,
    #[doc = "Engine version that ran it."]
    pub validator: ::std::string::String,
}
#[doc = "The tree the command ran on: HEAD, and a digest of every tracked change plus every untracked file."]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug, PartialEq)]
pub struct VerificationRecordedPayloadChecked {
    pub head: ::std::string::String,
    pub tree: ::std::string::String,
}
#[doc = "`VerificationResult`"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum VerificationResult {
    #[serde(rename = "pass")]
    Pass,
    #[serde(rename = "fail")]
    Fail,
    #[serde(rename = "timeout")]
    Timeout,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "refused")]
    Refused,
}
impl ::std::fmt::Display for VerificationResult {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Pass => f.write_str("pass"),
            Self::Fail => f.write_str("fail"),
            Self::Timeout => f.write_str("timeout"),
            Self::Error => f.write_str("error"),
            Self::Refused => f.write_str("refused"),
        }
    }
}
impl ::std::str::FromStr for VerificationResult {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "pass" => Ok(Self::Pass),
            "fail" => Ok(Self::Fail),
            "timeout" => Ok(Self::Timeout),
            "error" => Ok(Self::Error),
            "refused" => Ok(Self::Refused),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for VerificationResult {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for VerificationResult {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = " Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
